// Code generated by ent, DO NOT EDIT.

package userreferralconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userreferralconfig type in the database.
	Label = "user_referral_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCommissionRateOverride holds the string denoting the commission_rate_override field in the database.
	FieldCommissionRateOverride = "commission_rate_override"
	// FieldRefereeBonusOverride holds the string denoting the referee_bonus_override field in the database.
	FieldRefereeBonusOverride = "referee_bonus_override"
	// FieldWithdrawalAllowed holds the string denoting the withdrawal_allowed field in the database.
	FieldWithdrawalAllowed = "withdrawal_allowed"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// Table holds the table name of the userreferralconfig in the database.
	Table = "user_referral_configs"
)

// Columns holds all SQL columns for userreferralconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldEnabled,
	FieldCommissionRateOverride,
	FieldRefereeBonusOverride,
	FieldWithdrawalAllowed,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultWithdrawalAllowed holds the default value on creation for the "withdrawal_allowed" field.
	DefaultWithdrawalAllowed bool
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
)

// OrderOption defines the ordering options for the UserReferralConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCommissionRateOverride orders the results by the commission_rate_override field.
func ByCommissionRateOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionRateOverride, opts...).ToFunc()
}

// ByRefereeBonusOverride orders the results by the referee_bonus_override field.
func ByRefereeBonusOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefereeBonusOverride, opts...).ToFunc()
}

// ByWithdrawalAllowed orders the results by the withdrawal_allowed field.
func ByWithdrawalAllowed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWithdrawalAllowed, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}
