// Code generated by ent, DO NOT EDIT.

package refundrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldUserID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldPaymentOrderID, v))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldInvoiceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldStatus, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldReason, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAmount, v))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAdminID, v))
}

// AdminNotes applies equality check predicate on the "admin_notes" field. It's identical to AdminNotesEQ.
func AdminNotes(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAdminNotes, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldUserID, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDContains applies the Contains predicate on the "payment_order_id" field.
func PaymentOrderIDContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldPaymentOrderID, v))
}

// PaymentOrderIDHasPrefix applies the HasPrefix predicate on the "payment_order_id" field.
func PaymentOrderIDHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldPaymentOrderID, v))
}

// PaymentOrderIDHasSuffix applies the HasSuffix predicate on the "payment_order_id" field.
func PaymentOrderIDHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldPaymentOrderID, v))
}

// PaymentOrderIDEqualFold applies the EqualFold predicate on the "payment_order_id" field.
func PaymentOrderIDEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldPaymentOrderID, v))
}

// PaymentOrderIDContainsFold applies the ContainsFold predicate on the "payment_order_id" field.
func PaymentOrderIDContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldPaymentOrderID, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldInvoiceID, v))
}

// InvoiceIDIsNil applies the IsNil predicate on the "invoice_id" field.
func InvoiceIDIsNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIsNull(FieldInvoiceID))
}

// InvoiceIDNotNil applies the NotNil predicate on the "invoice_id" field.
func InvoiceIDNotNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotNull(FieldInvoiceID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldStatus, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldReason, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldAmount, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldAdminID, v))
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldAdminID, v))
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldAdminID, v))
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v int64) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldAdminID, v))
}

// AdminIDIsNil applies the IsNil predicate on the "admin_id" field.
func AdminIDIsNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIsNull(FieldAdminID))
}

// AdminIDNotNil applies the NotNil predicate on the "admin_id" field.
func AdminIDNotNil() predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotNull(FieldAdminID))
}

// AdminNotesEQ applies the EQ predicate on the "admin_notes" field.
func AdminNotesEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldAdminNotes, v))
}

// AdminNotesNEQ applies the NEQ predicate on the "admin_notes" field.
func AdminNotesNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldAdminNotes, v))
}

// AdminNotesIn applies the In predicate on the "admin_notes" field.
func AdminNotesIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldAdminNotes, vs...))
}

// AdminNotesNotIn applies the NotIn predicate on the "admin_notes" field.
func AdminNotesNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldAdminNotes, vs...))
}

// AdminNotesGT applies the GT predicate on the "admin_notes" field.
func AdminNotesGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldAdminNotes, v))
}

// AdminNotesGTE applies the GTE predicate on the "admin_notes" field.
func AdminNotesGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldAdminNotes, v))
}

// AdminNotesLT applies the LT predicate on the "admin_notes" field.
func AdminNotesLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldAdminNotes, v))
}

// AdminNotesLTE applies the LTE predicate on the "admin_notes" field.
func AdminNotesLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldAdminNotes, v))
}

// AdminNotesContains applies the Contains predicate on the "admin_notes" field.
func AdminNotesContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldAdminNotes, v))
}

// AdminNotesHasPrefix applies the HasPrefix predicate on the "admin_notes" field.
func AdminNotesHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldAdminNotes, v))
}

// AdminNotesHasSuffix applies the HasSuffix predicate on the "admin_notes" field.
func AdminNotesHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldAdminNotes, v))
}

// AdminNotesEqualFold applies the EqualFold predicate on the "admin_notes" field.
func AdminNotesEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldAdminNotes, v))
}

// AdminNotesContainsFold applies the ContainsFold predicate on the "admin_notes" field.
func AdminNotesContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldAdminNotes, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.RefundRequest {
	return predicate.RefundRequest(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RefundRequest) predicate.RefundRequest {
	return predicate.RefundRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RefundRequest) predicate.RefundRequest {
	return predicate.RefundRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RefundRequest) predicate.RefundRequest {
	return predicate.RefundRequest(sql.NotPredicates(p))
}
