// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/invoiceitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceUpdate is the builder for updating Invoice entities.
type InvoiceUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceMutation
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (_u *InvoiceUpdate) Where(ps ...predicate.Invoice) *InvoiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceUpdate) SetUpdatedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceUpdate) SetUserID(v int64) *InvoiceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableUserID(v *int64) *InvoiceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *InvoiceUpdate) SetUserEmail(v string) *InvoiceUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableUserEmail(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetTitleType sets the "title_type" field.
func (_u *InvoiceUpdate) SetTitleType(v string) *InvoiceUpdate {
	_u.mutation.SetTitleType(v)
	return _u
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableTitleType(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetTitleType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceUpdate) SetTitle(v string) *InvoiceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableTitle(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNo sets the "tax_no" field.
func (_u *InvoiceUpdate) SetTaxNo(v string) *InvoiceUpdate {
	_u.mutation.SetTaxNo(v)
	return _u
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableTaxNo(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetTaxNo(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *InvoiceUpdate) SetContactEmail(v string) *InvoiceUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableContactEmail(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceUpdate) SetAmount(v float64) *InvoiceUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableAmount(v *float64) *InvoiceUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceUpdate) AddAmount(v float64) *InvoiceUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceUpdate) SetCurrency(v string) *InvoiceUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableCurrency(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InvoiceUpdate) SetNotes(v string) *InvoiceUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableNotes(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceUpdate) SetStatus(v string) *InvoiceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableStatus(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InvoiceUpdate) SetSubmittedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableSubmittedAt(v *time.Time) *InvoiceUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *InvoiceUpdate) SetReviewedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableReviewedAt(v *time.Time) *InvoiceUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *InvoiceUpdate) ClearReviewedAt() *InvoiceUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *InvoiceUpdate) SetReviewedBy(v int64) *InvoiceUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableReviewedBy(v *int64) *InvoiceUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *InvoiceUpdate) AddReviewedBy(v int64) *InvoiceUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *InvoiceUpdate) ClearReviewedBy() *InvoiceUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *InvoiceUpdate) SetReviewNotes(v string) *InvoiceUpdate {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableReviewNotes(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceUpdate) SetIssuedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableIssuedAt(v *time.Time) *InvoiceUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceUpdate) ClearIssuedAt() *InvoiceUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceUpdate) SetInvoiceNo(v string) *InvoiceUpdate {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableInvoiceNo(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetPdfPath sets the "pdf_path" field.
func (_u *InvoiceUpdate) SetPdfPath(v string) *InvoiceUpdate {
	_u.mutation.SetPdfPath(v)
	return _u
}

// SetNillablePdfPath sets the "pdf_path" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillablePdfPath(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetPdfPath(*v)
	}
	return _u
}

// SetPdfStorage sets the "pdf_storage" field.
func (_u *InvoiceUpdate) SetPdfStorage(v string) *InvoiceUpdate {
	_u.mutation.SetPdfStorage(v)
	return _u
}

// SetNillablePdfStorage sets the "pdf_storage" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillablePdfStorage(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetPdfStorage(*v)
	}
	return _u
}

// SetPdfSize sets the "pdf_size" field.
func (_u *InvoiceUpdate) SetPdfSize(v int64) *InvoiceUpdate {
	_u.mutation.ResetPdfSize()
	_u.mutation.SetPdfSize(v)
	return _u
}

// SetNillablePdfSize sets the "pdf_size" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillablePdfSize(v *int64) *InvoiceUpdate {
	if v != nil {
		_u.SetPdfSize(*v)
	}
	return _u
}

// AddPdfSize adds value to the "pdf_size" field.
func (_u *InvoiceUpdate) AddPdfSize(v int64) *InvoiceUpdate {
	_u.mutation.AddPdfSize(v)
	return _u
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (_u *InvoiceUpdate) SetPdfSha256(v string) *InvoiceUpdate {
	_u.mutation.SetPdfSha256(v)
	return _u
}

// SetNillablePdfSha256 sets the "pdf_sha256" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillablePdfSha256(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetPdfSha256(*v)
	}
	return _u
}

// SetPdfOriginalName sets the "pdf_original_name" field.
func (_u *InvoiceUpdate) SetPdfOriginalName(v string) *InvoiceUpdate {
	_u.mutation.SetPdfOriginalName(v)
	return _u
}

// SetNillablePdfOriginalName sets the "pdf_original_name" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillablePdfOriginalName(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetPdfOriginalName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InvoiceUpdate) SetProvider(v string) *InvoiceUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableProvider(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderPayload sets the "provider_payload" field.
func (_u *InvoiceUpdate) SetProviderPayload(v map[string]interface{}) *InvoiceUpdate {
	_u.mutation.SetProviderPayload(v)
	return _u
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (_u *InvoiceUpdate) ClearProviderPayload() *InvoiceUpdate {
	_u.mutation.ClearProviderPayload()
	return _u
}

// SetVoidedBy sets the "voided_by" field.
func (_u *InvoiceUpdate) SetVoidedBy(v int64) *InvoiceUpdate {
	_u.mutation.ResetVoidedBy()
	_u.mutation.SetVoidedBy(v)
	return _u
}

// SetNillableVoidedBy sets the "voided_by" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableVoidedBy(v *int64) *InvoiceUpdate {
	if v != nil {
		_u.SetVoidedBy(*v)
	}
	return _u
}

// AddVoidedBy adds value to the "voided_by" field.
func (_u *InvoiceUpdate) AddVoidedBy(v int64) *InvoiceUpdate {
	_u.mutation.AddVoidedBy(v)
	return _u
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (_u *InvoiceUpdate) ClearVoidedBy() *InvoiceUpdate {
	_u.mutation.ClearVoidedBy()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceUpdate) SetUser(v *User) *InvoiceUpdate {
	return _u.SetUserID(v.ID)
}

// AddItemIDs adds the "items" edge to the InvoiceItem entity by IDs.
func (_u *InvoiceUpdate) AddItemIDs(ids ...int64) *InvoiceUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdate) AddItems(v ...*InvoiceItem) *InvoiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_u *InvoiceUpdate) Mutation() *InvoiceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceUpdate) ClearUser() *InvoiceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearItems clears all "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdate) ClearItems() *InvoiceUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to InvoiceItem entities by IDs.
func (_u *InvoiceUpdate) RemoveItemIDs(ids ...int64) *InvoiceUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to InvoiceItem entities.
func (_u *InvoiceUpdate) RemoveItems(v ...*InvoiceItem) *InvoiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceUpdate) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := invoice.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TitleType(); ok {
		if err := invoice.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "Invoice.title_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoice.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Invoice.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNo(); ok {
		if err := invoice.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := invoice.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.contact_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Invoice.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoice.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfPath(); ok {
		if err := invoice.PdfPathValidator(v); err != nil {
			return &ValidationError{Name: "pdf_path", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfStorage(); ok {
		if err := invoice.PdfStorageValidator(v); err != nil {
			return &ValidationError{Name: "pdf_storage", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_storage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfSha256(); ok {
		if err := invoice.PdfSha256Validator(v); err != nil {
			return &ValidationError{Name: "pdf_sha256", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfOriginalName(); ok {
		if err := invoice.PdfOriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "pdf_original_name", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := invoice.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Invoice.provider": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invoice.user"`)
	}
	return nil
}

func (_u *InvoiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(invoice.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleType(); ok {
		_spec.SetField(invoice.FieldTitleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoice.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNo(); ok {
		_spec.SetField(invoice.FieldTaxNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(invoice.FieldContactEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(invoice.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(invoice.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(invoice.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(invoice.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(invoice.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(invoice.FieldReviewNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoice.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoice.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoice.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfPath(); ok {
		_spec.SetField(invoice.FieldPdfPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfStorage(); ok {
		_spec.SetField(invoice.FieldPdfStorage, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfSize(); ok {
		_spec.SetField(invoice.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPdfSize(); ok {
		_spec.AddField(invoice.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PdfSha256(); ok {
		_spec.SetField(invoice.FieldPdfSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfOriginalName(); ok {
		_spec.SetField(invoice.FieldPdfOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(invoice.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderPayload(); ok {
		_spec.SetField(invoice.FieldProviderPayload, field.TypeJSON, value)
	}
	if _u.mutation.ProviderPayloadCleared() {
		_spec.ClearField(invoice.FieldProviderPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.VoidedBy(); ok {
		_spec.SetField(invoice.FieldVoidedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVoidedBy(); ok {
		_spec.AddField(invoice.FieldVoidedBy, field.TypeInt64, value)
	}
	if _u.mutation.VoidedByCleared() {
		_spec.ClearField(invoice.FieldVoidedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.UserTable,
			Columns: []string{invoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.UserTable,
			Columns: []string{invoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceUpdateOne is the builder for updating a single Invoice entity.
type InvoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceUpdateOne) SetUpdatedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceUpdateOne) SetUserID(v int64) *InvoiceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableUserID(v *int64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *InvoiceUpdateOne) SetUserEmail(v string) *InvoiceUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableUserEmail(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetTitleType sets the "title_type" field.
func (_u *InvoiceUpdateOne) SetTitleType(v string) *InvoiceUpdateOne {
	_u.mutation.SetTitleType(v)
	return _u
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableTitleType(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetTitleType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceUpdateOne) SetTitle(v string) *InvoiceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableTitle(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNo sets the "tax_no" field.
func (_u *InvoiceUpdateOne) SetTaxNo(v string) *InvoiceUpdateOne {
	_u.mutation.SetTaxNo(v)
	return _u
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableTaxNo(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetTaxNo(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *InvoiceUpdateOne) SetContactEmail(v string) *InvoiceUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableContactEmail(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceUpdateOne) SetAmount(v float64) *InvoiceUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableAmount(v *float64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceUpdateOne) AddAmount(v float64) *InvoiceUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceUpdateOne) SetCurrency(v string) *InvoiceUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableCurrency(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InvoiceUpdateOne) SetNotes(v string) *InvoiceUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableNotes(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceUpdateOne) SetStatus(v string) *InvoiceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableStatus(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InvoiceUpdateOne) SetSubmittedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableSubmittedAt(v *time.Time) *InvoiceUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *InvoiceUpdateOne) SetReviewedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableReviewedAt(v *time.Time) *InvoiceUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *InvoiceUpdateOne) ClearReviewedAt() *InvoiceUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *InvoiceUpdateOne) SetReviewedBy(v int64) *InvoiceUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableReviewedBy(v *int64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *InvoiceUpdateOne) AddReviewedBy(v int64) *InvoiceUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *InvoiceUpdateOne) ClearReviewedBy() *InvoiceUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *InvoiceUpdateOne) SetReviewNotes(v string) *InvoiceUpdateOne {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableReviewNotes(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceUpdateOne) SetIssuedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableIssuedAt(v *time.Time) *InvoiceUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceUpdateOne) ClearIssuedAt() *InvoiceUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceUpdateOne) SetInvoiceNo(v string) *InvoiceUpdateOne {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableInvoiceNo(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetPdfPath sets the "pdf_path" field.
func (_u *InvoiceUpdateOne) SetPdfPath(v string) *InvoiceUpdateOne {
	_u.mutation.SetPdfPath(v)
	return _u
}

// SetNillablePdfPath sets the "pdf_path" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillablePdfPath(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetPdfPath(*v)
	}
	return _u
}

// SetPdfStorage sets the "pdf_storage" field.
func (_u *InvoiceUpdateOne) SetPdfStorage(v string) *InvoiceUpdateOne {
	_u.mutation.SetPdfStorage(v)
	return _u
}

// SetNillablePdfStorage sets the "pdf_storage" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillablePdfStorage(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetPdfStorage(*v)
	}
	return _u
}

// SetPdfSize sets the "pdf_size" field.
func (_u *InvoiceUpdateOne) SetPdfSize(v int64) *InvoiceUpdateOne {
	_u.mutation.ResetPdfSize()
	_u.mutation.SetPdfSize(v)
	return _u
}

// SetNillablePdfSize sets the "pdf_size" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillablePdfSize(v *int64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetPdfSize(*v)
	}
	return _u
}

// AddPdfSize adds value to the "pdf_size" field.
func (_u *InvoiceUpdateOne) AddPdfSize(v int64) *InvoiceUpdateOne {
	_u.mutation.AddPdfSize(v)
	return _u
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (_u *InvoiceUpdateOne) SetPdfSha256(v string) *InvoiceUpdateOne {
	_u.mutation.SetPdfSha256(v)
	return _u
}

// SetNillablePdfSha256 sets the "pdf_sha256" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillablePdfSha256(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetPdfSha256(*v)
	}
	return _u
}

// SetPdfOriginalName sets the "pdf_original_name" field.
func (_u *InvoiceUpdateOne) SetPdfOriginalName(v string) *InvoiceUpdateOne {
	_u.mutation.SetPdfOriginalName(v)
	return _u
}

// SetNillablePdfOriginalName sets the "pdf_original_name" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillablePdfOriginalName(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetPdfOriginalName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InvoiceUpdateOne) SetProvider(v string) *InvoiceUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableProvider(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderPayload sets the "provider_payload" field.
func (_u *InvoiceUpdateOne) SetProviderPayload(v map[string]interface{}) *InvoiceUpdateOne {
	_u.mutation.SetProviderPayload(v)
	return _u
}

// ClearProviderPayload clears the value of the "provider_payload" field.
func (_u *InvoiceUpdateOne) ClearProviderPayload() *InvoiceUpdateOne {
	_u.mutation.ClearProviderPayload()
	return _u
}

// SetVoidedBy sets the "voided_by" field.
func (_u *InvoiceUpdateOne) SetVoidedBy(v int64) *InvoiceUpdateOne {
	_u.mutation.ResetVoidedBy()
	_u.mutation.SetVoidedBy(v)
	return _u
}

// SetNillableVoidedBy sets the "voided_by" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableVoidedBy(v *int64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetVoidedBy(*v)
	}
	return _u
}

// AddVoidedBy adds value to the "voided_by" field.
func (_u *InvoiceUpdateOne) AddVoidedBy(v int64) *InvoiceUpdateOne {
	_u.mutation.AddVoidedBy(v)
	return _u
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (_u *InvoiceUpdateOne) ClearVoidedBy() *InvoiceUpdateOne {
	_u.mutation.ClearVoidedBy()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceUpdateOne) SetUser(v *User) *InvoiceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddItemIDs adds the "items" edge to the InvoiceItem entity by IDs.
func (_u *InvoiceUpdateOne) AddItemIDs(ids ...int64) *InvoiceUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdateOne) AddItems(v ...*InvoiceItem) *InvoiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_u *InvoiceUpdateOne) Mutation() *InvoiceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceUpdateOne) ClearUser() *InvoiceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearItems clears all "items" edges to the InvoiceItem entity.
func (_u *InvoiceUpdateOne) ClearItems() *InvoiceUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to InvoiceItem entities by IDs.
func (_u *InvoiceUpdateOne) RemoveItemIDs(ids ...int64) *InvoiceUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to InvoiceItem entities.
func (_u *InvoiceUpdateOne) RemoveItems(v ...*InvoiceItem) *InvoiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (_u *InvoiceUpdateOne) Where(ps ...predicate.Invoice) *InvoiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceUpdateOne) Select(field string, fields ...string) *InvoiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invoice entity.
func (_u *InvoiceUpdateOne) Save(ctx context.Context) (*Invoice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceUpdateOne) SaveX(ctx context.Context) *Invoice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceUpdateOne) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := invoice.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TitleType(); ok {
		if err := invoice.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "Invoice.title_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoice.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Invoice.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNo(); ok {
		if err := invoice.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := invoice.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "Invoice.contact_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Invoice.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoice.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "Invoice.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfPath(); ok {
		if err := invoice.PdfPathValidator(v); err != nil {
			return &ValidationError{Name: "pdf_path", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfStorage(); ok {
		if err := invoice.PdfStorageValidator(v); err != nil {
			return &ValidationError{Name: "pdf_storage", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_storage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfSha256(); ok {
		if err := invoice.PdfSha256Validator(v); err != nil {
			return &ValidationError{Name: "pdf_sha256", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfOriginalName(); ok {
		if err := invoice.PdfOriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "pdf_original_name", err: fmt.Errorf(`ent: validator failed for field "Invoice.pdf_original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := invoice.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Invoice.provider": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invoice.user"`)
	}
	return nil
}

func (_u *InvoiceUpdateOne) sqlSave(ctx context.Context) (_node *Invoice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invoice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoice.FieldID)
		for _, f := range fields {
			if !invoice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(invoice.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleType(); ok {
		_spec.SetField(invoice.FieldTitleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoice.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNo(); ok {
		_spec.SetField(invoice.FieldTaxNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(invoice.FieldContactEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(invoice.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(invoice.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(invoice.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(invoice.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(invoice.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(invoice.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(invoice.FieldReviewNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoice.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoice.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoice.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfPath(); ok {
		_spec.SetField(invoice.FieldPdfPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfStorage(); ok {
		_spec.SetField(invoice.FieldPdfStorage, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfSize(); ok {
		_spec.SetField(invoice.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPdfSize(); ok {
		_spec.AddField(invoice.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PdfSha256(); ok {
		_spec.SetField(invoice.FieldPdfSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfOriginalName(); ok {
		_spec.SetField(invoice.FieldPdfOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(invoice.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderPayload(); ok {
		_spec.SetField(invoice.FieldProviderPayload, field.TypeJSON, value)
	}
	if _u.mutation.ProviderPayloadCleared() {
		_spec.ClearField(invoice.FieldProviderPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.VoidedBy(); ok {
		_spec.SetField(invoice.FieldVoidedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVoidedBy(); ok {
		_spec.AddField(invoice.FieldVoidedBy, field.TypeInt64, value)
	}
	if _u.mutation.VoidedByCleared() {
		_spec.ClearField(invoice.FieldVoidedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.UserTable,
			Columns: []string{invoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.UserTable,
			Columns: []string{invoice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoice.ItemsTable,
			Columns: []string{invoice.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invoice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
