// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoice"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// Invoice is the model entity for the Invoice schema.
type Invoice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// 申请时邮箱快照
	UserEmail string `json:"user_email,omitempty"`
	// 内部申请单号，创建后回填，与平台 invoice_no 区分
	ApplicationNo string `json:"application_no,omitempty"`
	// personal | business
	TitleType string `json:"title_type,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// 企业必填，个人空串
	TaxNo string `json:"tax_no,omitempty"`
	// 收票邮箱（可选）
	ContactEmail string `json:"contact_email,omitempty"`
	// 购方地址（专票必填）
	BuyerAddress string `json:"buyer_address,omitempty"`
	// 购方电话（专票必填）
	BuyerPhone string `json:"buyer_phone,omitempty"`
	// 购方开户行（专票必填）
	BuyerBankName string `json:"buyer_bank_name,omitempty"`
	// 购方银行账号（专票必填）
	BuyerBankAccount string `json:"buyer_bank_account,omitempty"`
	// 订单 pay_amount 之和，RMB 元
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// pending | approved | issued | rejected | voided
	Status string `json:"status,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt time.Time `json:"submitted_at,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// admin user id
	ReviewedBy *int64 `json:"reviewed_by,omitempty"`
	// 驳回/作废原因
	ReviewNotes string `json:"review_notes,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// 真实发票号（管理员填写）
	InvoiceNo string `json:"invoice_no,omitempty"`
	// 存储路径或 S3 key
	PdfPath string `json:"pdf_path,omitempty"`
	// local | s3
	PdfStorage string `json:"pdf_storage,omitempty"`
	// PdfSize holds the value of the "pdf_size" field.
	PdfSize int64 `json:"pdf_size,omitempty"`
	// PdfSha256 holds the value of the "pdf_sha256" field.
	PdfSha256 string `json:"pdf_sha256,omitempty"`
	// PdfOriginalName holds the value of the "pdf_original_name" field.
	PdfOriginalName string `json:"pdf_original_name,omitempty"`
	// normal 普票 | special 专票
	InvoiceKind string `json:"invoice_kind,omitempty"`
	// 财云通 InvoiceType 枚举：04/10/01/08/05/06
	InvoiceTypeCode string `json:"invoice_type_code,omitempty"`
	// manual | caiyuntong | nuonuo | baiwang | ...
	Provider string `json:"provider,omitempty"`
	// none | queued | issuing | success | failed | reverse_pending | reversing | reverse_success | reverse_failed
	ProviderState string `json:"provider_state,omitempty"`
	// 蓝票 RequestID
	ProviderTraceID string `json:"provider_trace_id,omitempty"`
	// ProviderLastError holds the value of the "provider_last_error" field.
	ProviderLastError string `json:"provider_last_error,omitempty"`
	// ProviderRetryCount holds the value of the "provider_retry_count" field.
	ProviderRetryCount int `json:"provider_retry_count,omitempty"`
	// ProviderPayload holds the value of the "provider_payload" field.
	ProviderPayload map[string]interface{} `json:"provider_payload,omitempty"`
	// red_applying | red_confirmed | red_issuing | red_done
	ReverseStep string `json:"reverse_step,omitempty"`
	// 红字信息单编号（数电 Step 1 产物）
	RedAdviceNum string `json:"red_advice_num,omitempty"`
	// 红字信息单 uuid（数电 Step 2 产物）
	RedConfirmNum string `json:"red_confirm_num,omitempty"`
	// 红票 RequestID
	ReverseTraceID string `json:"reverse_trace_id,omitempty"`
	// 红票号码
	RedInvoiceNo string `json:"red_invoice_no,omitempty"`
	// 红票 PDF 存储路径
	RedPdfPath string `json:"red_pdf_path,omitempty"`
	// VoidedBy holds the value of the "voided_by" field.
	VoidedBy *int64 `json:"voided_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceQuery when eager-loading is set.
	Edges        InvoiceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceEdges holds the relations/edges for other nodes in the graph.
type InvoiceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Items holds the value of the items edge.
	Items []*InvoiceItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceEdges) ItemsOrErr() ([]*InvoiceItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invoice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoice.FieldProviderPayload:
			values[i] = new([]byte)
		case invoice.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case invoice.FieldID, invoice.FieldUserID, invoice.FieldReviewedBy, invoice.FieldPdfSize, invoice.FieldProviderRetryCount, invoice.FieldVoidedBy:
			values[i] = new(sql.NullInt64)
		case invoice.FieldUserEmail, invoice.FieldApplicationNo, invoice.FieldTitleType, invoice.FieldTitle, invoice.FieldTaxNo, invoice.FieldContactEmail, invoice.FieldBuyerAddress, invoice.FieldBuyerPhone, invoice.FieldBuyerBankName, invoice.FieldBuyerBankAccount, invoice.FieldCurrency, invoice.FieldNotes, invoice.FieldStatus, invoice.FieldReviewNotes, invoice.FieldInvoiceNo, invoice.FieldPdfPath, invoice.FieldPdfStorage, invoice.FieldPdfSha256, invoice.FieldPdfOriginalName, invoice.FieldInvoiceKind, invoice.FieldInvoiceTypeCode, invoice.FieldProvider, invoice.FieldProviderState, invoice.FieldProviderTraceID, invoice.FieldProviderLastError, invoice.FieldReverseStep, invoice.FieldRedAdviceNum, invoice.FieldRedConfirmNum, invoice.FieldReverseTraceID, invoice.FieldRedInvoiceNo, invoice.FieldRedPdfPath:
			values[i] = new(sql.NullString)
		case invoice.FieldCreatedAt, invoice.FieldUpdatedAt, invoice.FieldSubmittedAt, invoice.FieldReviewedAt, invoice.FieldIssuedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invoice fields.
func (_m *Invoice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case invoice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoice.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case invoice.FieldApplicationNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_no", values[i])
			} else if value.Valid {
				_m.ApplicationNo = value.String
			}
		case invoice.FieldTitleType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_type", values[i])
			} else if value.Valid {
				_m.TitleType = value.String
			}
		case invoice.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case invoice.FieldTaxNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_no", values[i])
			} else if value.Valid {
				_m.TaxNo = value.String
			}
		case invoice.FieldContactEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_email", values[i])
			} else if value.Valid {
				_m.ContactEmail = value.String
			}
		case invoice.FieldBuyerAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_address", values[i])
			} else if value.Valid {
				_m.BuyerAddress = value.String
			}
		case invoice.FieldBuyerPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_phone", values[i])
			} else if value.Valid {
				_m.BuyerPhone = value.String
			}
		case invoice.FieldBuyerBankName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_bank_name", values[i])
			} else if value.Valid {
				_m.BuyerBankName = value.String
			}
		case invoice.FieldBuyerBankAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_bank_account", values[i])
			} else if value.Valid {
				_m.BuyerBankAccount = value.String
			}
		case invoice.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case invoice.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case invoice.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case invoice.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoice.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = value.Time
			}
		case invoice.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case invoice.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = new(int64)
				*_m.ReviewedBy = value.Int64
			}
		case invoice.FieldReviewNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_notes", values[i])
			} else if value.Valid {
				_m.ReviewNotes = value.String
			}
		case invoice.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case invoice.FieldInvoiceNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_no", values[i])
			} else if value.Valid {
				_m.InvoiceNo = value.String
			}
		case invoice.FieldPdfPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_path", values[i])
			} else if value.Valid {
				_m.PdfPath = value.String
			}
		case invoice.FieldPdfStorage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_storage", values[i])
			} else if value.Valid {
				_m.PdfStorage = value.String
			}
		case invoice.FieldPdfSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_size", values[i])
			} else if value.Valid {
				_m.PdfSize = value.Int64
			}
		case invoice.FieldPdfSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_sha256", values[i])
			} else if value.Valid {
				_m.PdfSha256 = value.String
			}
		case invoice.FieldPdfOriginalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_original_name", values[i])
			} else if value.Valid {
				_m.PdfOriginalName = value.String
			}
		case invoice.FieldInvoiceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_kind", values[i])
			} else if value.Valid {
				_m.InvoiceKind = value.String
			}
		case invoice.FieldInvoiceTypeCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_type_code", values[i])
			} else if value.Valid {
				_m.InvoiceTypeCode = value.String
			}
		case invoice.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case invoice.FieldProviderState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_state", values[i])
			} else if value.Valid {
				_m.ProviderState = value.String
			}
		case invoice.FieldProviderTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_trace_id", values[i])
			} else if value.Valid {
				_m.ProviderTraceID = value.String
			}
		case invoice.FieldProviderLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_last_error", values[i])
			} else if value.Valid {
				_m.ProviderLastError = value.String
			}
		case invoice.FieldProviderRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_retry_count", values[i])
			} else if value.Valid {
				_m.ProviderRetryCount = int(value.Int64)
			}
		case invoice.FieldProviderPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProviderPayload); err != nil {
					return fmt.Errorf("unmarshal field provider_payload: %w", err)
				}
			}
		case invoice.FieldReverseStep:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reverse_step", values[i])
			} else if value.Valid {
				_m.ReverseStep = value.String
			}
		case invoice.FieldRedAdviceNum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field red_advice_num", values[i])
			} else if value.Valid {
				_m.RedAdviceNum = value.String
			}
		case invoice.FieldRedConfirmNum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field red_confirm_num", values[i])
			} else if value.Valid {
				_m.RedConfirmNum = value.String
			}
		case invoice.FieldReverseTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reverse_trace_id", values[i])
			} else if value.Valid {
				_m.ReverseTraceID = value.String
			}
		case invoice.FieldRedInvoiceNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field red_invoice_no", values[i])
			} else if value.Valid {
				_m.RedInvoiceNo = value.String
			}
		case invoice.FieldRedPdfPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field red_pdf_path", values[i])
			} else if value.Valid {
				_m.RedPdfPath = value.String
			}
		case invoice.FieldVoidedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field voided_by", values[i])
			} else if value.Valid {
				_m.VoidedBy = new(int64)
				*_m.VoidedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invoice.
// This includes values selected through modifiers, order, etc.
func (_m *Invoice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Invoice entity.
func (_m *Invoice) QueryUser() *UserQuery {
	return NewInvoiceClient(_m.config).QueryUser(_m)
}

// QueryItems queries the "items" edge of the Invoice entity.
func (_m *Invoice) QueryItems() *InvoiceItemQuery {
	return NewInvoiceClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this Invoice.
// Note that you need to call Invoice.Unwrap() before calling this method if this Invoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Invoice) Update() *InvoiceUpdateOne {
	return NewInvoiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Invoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Invoice) Unwrap() *Invoice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invoice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Invoice) String() string {
	var builder strings.Builder
	builder.WriteString("Invoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("application_no=")
	builder.WriteString(_m.ApplicationNo)
	builder.WriteString(", ")
	builder.WriteString("title_type=")
	builder.WriteString(_m.TitleType)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("tax_no=")
	builder.WriteString(_m.TaxNo)
	builder.WriteString(", ")
	builder.WriteString("contact_email=")
	builder.WriteString(_m.ContactEmail)
	builder.WriteString(", ")
	builder.WriteString("buyer_address=")
	builder.WriteString(_m.BuyerAddress)
	builder.WriteString(", ")
	builder.WriteString("buyer_phone=")
	builder.WriteString(_m.BuyerPhone)
	builder.WriteString(", ")
	builder.WriteString("buyer_bank_name=")
	builder.WriteString(_m.BuyerBankName)
	builder.WriteString(", ")
	builder.WriteString("buyer_bank_account=")
	builder.WriteString(_m.BuyerBankAccount)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(_m.SubmittedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedBy; v != nil {
		builder.WriteString("reviewed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("review_notes=")
	builder.WriteString(_m.ReviewNotes)
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("invoice_no=")
	builder.WriteString(_m.InvoiceNo)
	builder.WriteString(", ")
	builder.WriteString("pdf_path=")
	builder.WriteString(_m.PdfPath)
	builder.WriteString(", ")
	builder.WriteString("pdf_storage=")
	builder.WriteString(_m.PdfStorage)
	builder.WriteString(", ")
	builder.WriteString("pdf_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.PdfSize))
	builder.WriteString(", ")
	builder.WriteString("pdf_sha256=")
	builder.WriteString(_m.PdfSha256)
	builder.WriteString(", ")
	builder.WriteString("pdf_original_name=")
	builder.WriteString(_m.PdfOriginalName)
	builder.WriteString(", ")
	builder.WriteString("invoice_kind=")
	builder.WriteString(_m.InvoiceKind)
	builder.WriteString(", ")
	builder.WriteString("invoice_type_code=")
	builder.WriteString(_m.InvoiceTypeCode)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_state=")
	builder.WriteString(_m.ProviderState)
	builder.WriteString(", ")
	builder.WriteString("provider_trace_id=")
	builder.WriteString(_m.ProviderTraceID)
	builder.WriteString(", ")
	builder.WriteString("provider_last_error=")
	builder.WriteString(_m.ProviderLastError)
	builder.WriteString(", ")
	builder.WriteString("provider_retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderRetryCount))
	builder.WriteString(", ")
	builder.WriteString("provider_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderPayload))
	builder.WriteString(", ")
	builder.WriteString("reverse_step=")
	builder.WriteString(_m.ReverseStep)
	builder.WriteString(", ")
	builder.WriteString("red_advice_num=")
	builder.WriteString(_m.RedAdviceNum)
	builder.WriteString(", ")
	builder.WriteString("red_confirm_num=")
	builder.WriteString(_m.RedConfirmNum)
	builder.WriteString(", ")
	builder.WriteString("reverse_trace_id=")
	builder.WriteString(_m.ReverseTraceID)
	builder.WriteString(", ")
	builder.WriteString("red_invoice_no=")
	builder.WriteString(_m.RedInvoiceNo)
	builder.WriteString(", ")
	builder.WriteString("red_pdf_path=")
	builder.WriteString(_m.RedPdfPath)
	builder.WriteString(", ")
	if v := _m.VoidedBy; v != nil {
		builder.WriteString("voided_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Invoices is a parsable slice of Invoice.
type Invoices []*Invoice
