// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicevoidrequest"
)

// InvoiceVoidRequestCreate is the builder for creating a InvoiceVoidRequest entity.
type InvoiceVoidRequestCreate struct {
	config
	mutation *InvoiceVoidRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceVoidRequestCreate) SetCreatedAt(v time.Time) *InvoiceVoidRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceVoidRequestCreate) SetUpdatedAt(v time.Time) *InvoiceVoidRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceVoidRequestCreate) SetUserID(v int64) *InvoiceVoidRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInvoiceID sets the "invoice_id" field.
func (_c *InvoiceVoidRequestCreate) SetInvoiceID(v int64) *InvoiceVoidRequestCreate {
	_c.mutation.SetInvoiceID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceVoidRequestCreate) SetStatus(v string) *InvoiceVoidRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableStatus(v *string) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *InvoiceVoidRequestCreate) SetReason(v string) *InvoiceVoidRequestCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableReason(v *string) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetAdminID sets the "admin_id" field.
func (_c *InvoiceVoidRequestCreate) SetAdminID(v int64) *InvoiceVoidRequestCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableAdminID(v *int64) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetAdminID(*v)
	}
	return _c
}

// SetAdminNotes sets the "admin_notes" field.
func (_c *InvoiceVoidRequestCreate) SetAdminNotes(v string) *InvoiceVoidRequestCreate {
	_c.mutation.SetAdminNotes(v)
	return _c
}

// SetNillableAdminNotes sets the "admin_notes" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableAdminNotes(v *string) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetAdminNotes(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *InvoiceVoidRequestCreate) SetReviewedAt(v time.Time) *InvoiceVoidRequestCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *InvoiceVoidRequestCreate) SetNillableReviewedAt(v *time.Time) *InvoiceVoidRequestCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceVoidRequestMutation object of the builder.
func (_c *InvoiceVoidRequestCreate) Mutation() *InvoiceVoidRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceVoidRequest in the database.
func (_c *InvoiceVoidRequestCreate) Save(ctx context.Context) (*InvoiceVoidRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceVoidRequestCreate) SaveX(ctx context.Context) *InvoiceVoidRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceVoidRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceVoidRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceVoidRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicevoidrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicevoidrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicevoidrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := invoicevoidrequest.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.AdminNotes(); !ok {
		v := invoicevoidrequest.DefaultAdminNotes
		_c.mutation.SetAdminNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceVoidRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceVoidRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceVoidRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceVoidRequest.user_id"`)}
	}
	if _, ok := _c.mutation.InvoiceID(); !ok {
		return &ValidationError{Name: "invoice_id", err: errors.New(`ent: missing required field "InvoiceVoidRequest.invoice_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceVoidRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicevoidrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceVoidRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "InvoiceVoidRequest.reason"`)}
	}
	if _, ok := _c.mutation.AdminNotes(); !ok {
		return &ValidationError{Name: "admin_notes", err: errors.New(`ent: missing required field "InvoiceVoidRequest.admin_notes"`)}
	}
	return nil
}

func (_c *InvoiceVoidRequestCreate) sqlSave(ctx context.Context) (*InvoiceVoidRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceVoidRequestCreate) createSpec() (*InvoiceVoidRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceVoidRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicevoidrequest.Table, sqlgraph.NewFieldSpec(invoicevoidrequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicevoidrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicevoidrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoicevoidrequest.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.InvoiceID(); ok {
		_spec.SetField(invoicevoidrequest.FieldInvoiceID, field.TypeInt64, value)
		_node.InvoiceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicevoidrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(invoicevoidrequest.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.AdminID(); ok {
		_spec.SetField(invoicevoidrequest.FieldAdminID, field.TypeInt64, value)
		_node.AdminID = &value
	}
	if value, ok := _c.mutation.AdminNotes(); ok {
		_spec.SetField(invoicevoidrequest.FieldAdminNotes, field.TypeString, value)
		_node.AdminNotes = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(invoicevoidrequest.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceVoidRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceVoidRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceVoidRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceVoidRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceVoidRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceVoidRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceVoidRequestCreate) OnConflictColumns(columns ...string) *InvoiceVoidRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceVoidRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceVoidRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceVoidRequest node.
	InvoiceVoidRequestUpsertOne struct {
		create *InvoiceVoidRequestCreate
	}

	// InvoiceVoidRequestUpsert is the "OnConflict" setter.
	InvoiceVoidRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceVoidRequestUpsert) SetUpdatedAt(v time.Time) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateUpdatedAt() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceVoidRequestUpsert) SetUserID(v int64) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateUserID() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceVoidRequestUpsert) AddUserID(v int64) *InvoiceVoidRequestUpsert {
	u.Add(invoicevoidrequest.FieldUserID, v)
	return u
}

// SetInvoiceID sets the "invoice_id" field.
func (u *InvoiceVoidRequestUpsert) SetInvoiceID(v int64) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldInvoiceID, v)
	return u
}

// UpdateInvoiceID sets the "invoice_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateInvoiceID() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldInvoiceID)
	return u
}

// AddInvoiceID adds v to the "invoice_id" field.
func (u *InvoiceVoidRequestUpsert) AddInvoiceID(v int64) *InvoiceVoidRequestUpsert {
	u.Add(invoicevoidrequest.FieldInvoiceID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceVoidRequestUpsert) SetStatus(v string) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateStatus() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *InvoiceVoidRequestUpsert) SetReason(v string) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateReason() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldReason)
	return u
}

// SetAdminID sets the "admin_id" field.
func (u *InvoiceVoidRequestUpsert) SetAdminID(v int64) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldAdminID, v)
	return u
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateAdminID() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldAdminID)
	return u
}

// AddAdminID adds v to the "admin_id" field.
func (u *InvoiceVoidRequestUpsert) AddAdminID(v int64) *InvoiceVoidRequestUpsert {
	u.Add(invoicevoidrequest.FieldAdminID, v)
	return u
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *InvoiceVoidRequestUpsert) ClearAdminID() *InvoiceVoidRequestUpsert {
	u.SetNull(invoicevoidrequest.FieldAdminID)
	return u
}

// SetAdminNotes sets the "admin_notes" field.
func (u *InvoiceVoidRequestUpsert) SetAdminNotes(v string) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldAdminNotes, v)
	return u
}

// UpdateAdminNotes sets the "admin_notes" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateAdminNotes() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldAdminNotes)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceVoidRequestUpsert) SetReviewedAt(v time.Time) *InvoiceVoidRequestUpsert {
	u.Set(invoicevoidrequest.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsert) UpdateReviewedAt() *InvoiceVoidRequestUpsert {
	u.SetExcluded(invoicevoidrequest.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceVoidRequestUpsert) ClearReviewedAt() *InvoiceVoidRequestUpsert {
	u.SetNull(invoicevoidrequest.FieldReviewedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceVoidRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceVoidRequestUpsertOne) UpdateNewValues() *InvoiceVoidRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicevoidrequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceVoidRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceVoidRequestUpsertOne) Ignore() *InvoiceVoidRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceVoidRequestUpsertOne) DoNothing() *InvoiceVoidRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceVoidRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceVoidRequestUpsertOne) Update(set func(*InvoiceVoidRequestUpsert)) *InvoiceVoidRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceVoidRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceVoidRequestUpsertOne) SetUpdatedAt(v time.Time) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateUpdatedAt() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceVoidRequestUpsertOne) SetUserID(v int64) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceVoidRequestUpsertOne) AddUserID(v int64) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateUserID() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetInvoiceID sets the "invoice_id" field.
func (u *InvoiceVoidRequestUpsertOne) SetInvoiceID(v int64) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetInvoiceID(v)
	})
}

// AddInvoiceID adds v to the "invoice_id" field.
func (u *InvoiceVoidRequestUpsertOne) AddInvoiceID(v int64) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.AddInvoiceID(v)
	})
}

// UpdateInvoiceID sets the "invoice_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateInvoiceID() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateInvoiceID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceVoidRequestUpsertOne) SetStatus(v string) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateStatus() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *InvoiceVoidRequestUpsertOne) SetReason(v string) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateReason() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateReason()
	})
}

// SetAdminID sets the "admin_id" field.
func (u *InvoiceVoidRequestUpsertOne) SetAdminID(v int64) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetAdminID(v)
	})
}

// AddAdminID adds v to the "admin_id" field.
func (u *InvoiceVoidRequestUpsertOne) AddAdminID(v int64) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.AddAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateAdminID() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *InvoiceVoidRequestUpsertOne) ClearAdminID() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.ClearAdminID()
	})
}

// SetAdminNotes sets the "admin_notes" field.
func (u *InvoiceVoidRequestUpsertOne) SetAdminNotes(v string) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetAdminNotes(v)
	})
}

// UpdateAdminNotes sets the "admin_notes" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateAdminNotes() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateAdminNotes()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceVoidRequestUpsertOne) SetReviewedAt(v time.Time) *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertOne) UpdateReviewedAt() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceVoidRequestUpsertOne) ClearReviewedAt() *InvoiceVoidRequestUpsertOne {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// Exec executes the query.
func (u *InvoiceVoidRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceVoidRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceVoidRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceVoidRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceVoidRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceVoidRequestCreateBulk is the builder for creating many InvoiceVoidRequest entities in bulk.
type InvoiceVoidRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceVoidRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceVoidRequest entities in the database.
func (_c *InvoiceVoidRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceVoidRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceVoidRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceVoidRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceVoidRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceVoidRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceVoidRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceVoidRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceVoidRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceVoidRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceVoidRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceVoidRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceVoidRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceVoidRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceVoidRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceVoidRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceVoidRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceVoidRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceVoidRequest nodes.
type InvoiceVoidRequestUpsertBulk struct {
	create *InvoiceVoidRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceVoidRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceVoidRequestUpsertBulk) UpdateNewValues() *InvoiceVoidRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicevoidrequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceVoidRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceVoidRequestUpsertBulk) Ignore() *InvoiceVoidRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceVoidRequestUpsertBulk) DoNothing() *InvoiceVoidRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceVoidRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceVoidRequestUpsertBulk) Update(set func(*InvoiceVoidRequestUpsert)) *InvoiceVoidRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceVoidRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceVoidRequestUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateUpdatedAt() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceVoidRequestUpsertBulk) SetUserID(v int64) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceVoidRequestUpsertBulk) AddUserID(v int64) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateUserID() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetInvoiceID sets the "invoice_id" field.
func (u *InvoiceVoidRequestUpsertBulk) SetInvoiceID(v int64) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetInvoiceID(v)
	})
}

// AddInvoiceID adds v to the "invoice_id" field.
func (u *InvoiceVoidRequestUpsertBulk) AddInvoiceID(v int64) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.AddInvoiceID(v)
	})
}

// UpdateInvoiceID sets the "invoice_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateInvoiceID() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateInvoiceID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceVoidRequestUpsertBulk) SetStatus(v string) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateStatus() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *InvoiceVoidRequestUpsertBulk) SetReason(v string) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateReason() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateReason()
	})
}

// SetAdminID sets the "admin_id" field.
func (u *InvoiceVoidRequestUpsertBulk) SetAdminID(v int64) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetAdminID(v)
	})
}

// AddAdminID adds v to the "admin_id" field.
func (u *InvoiceVoidRequestUpsertBulk) AddAdminID(v int64) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.AddAdminID(v)
	})
}

// UpdateAdminID sets the "admin_id" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateAdminID() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateAdminID()
	})
}

// ClearAdminID clears the value of the "admin_id" field.
func (u *InvoiceVoidRequestUpsertBulk) ClearAdminID() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.ClearAdminID()
	})
}

// SetAdminNotes sets the "admin_notes" field.
func (u *InvoiceVoidRequestUpsertBulk) SetAdminNotes(v string) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetAdminNotes(v)
	})
}

// UpdateAdminNotes sets the "admin_notes" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateAdminNotes() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateAdminNotes()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceVoidRequestUpsertBulk) SetReviewedAt(v time.Time) *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceVoidRequestUpsertBulk) UpdateReviewedAt() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceVoidRequestUpsertBulk) ClearReviewedAt() *InvoiceVoidRequestUpsertBulk {
	return u.Update(func(s *InvoiceVoidRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// Exec executes the query.
func (u *InvoiceVoidRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceVoidRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceVoidRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceVoidRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
