// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoicevoidrequest"
)

// InvoiceVoidRequest is the model entity for the InvoiceVoidRequest schema.
type InvoiceVoidRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 申请人
	UserID int64 `json:"user_id,omitempty"`
	// 关联发票（必有）
	InvoiceID int64 `json:"invoice_id,omitempty"`
	// pending_review | approved | rejected
	Status string `json:"status,omitempty"`
	// 用户填写的作废原因
	Reason string `json:"reason,omitempty"`
	// 审批管理员
	AdminID *int64 `json:"admin_id,omitempty"`
	// 管理员备注（驳回理由）
	AdminNotes string `json:"admin_notes,omitempty"`
	// 审批时间
	ReviewedAt   *time.Time `json:"reviewed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceVoidRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicevoidrequest.FieldID, invoicevoidrequest.FieldUserID, invoicevoidrequest.FieldInvoiceID, invoicevoidrequest.FieldAdminID:
			values[i] = new(sql.NullInt64)
		case invoicevoidrequest.FieldStatus, invoicevoidrequest.FieldReason, invoicevoidrequest.FieldAdminNotes:
			values[i] = new(sql.NullString)
		case invoicevoidrequest.FieldCreatedAt, invoicevoidrequest.FieldUpdatedAt, invoicevoidrequest.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceVoidRequest fields.
func (_m *InvoiceVoidRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicevoidrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicevoidrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoicevoidrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case invoicevoidrequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoicevoidrequest.FieldInvoiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_id", values[i])
			} else if value.Valid {
				_m.InvoiceID = value.Int64
			}
		case invoicevoidrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoicevoidrequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case invoicevoidrequest.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = new(int64)
				*_m.AdminID = value.Int64
			}
		case invoicevoidrequest.FieldAdminNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_notes", values[i])
			} else if value.Valid {
				_m.AdminNotes = value.String
			}
		case invoicevoidrequest.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceVoidRequest.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceVoidRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InvoiceVoidRequest.
// Note that you need to call InvoiceVoidRequest.Unwrap() before calling this method if this InvoiceVoidRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceVoidRequest) Update() *InvoiceVoidRequestUpdateOne {
	return NewInvoiceVoidRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceVoidRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceVoidRequest) Unwrap() *InvoiceVoidRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceVoidRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceVoidRequest) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceVoidRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("invoice_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.AdminID; v != nil {
		builder.WriteString("admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("admin_notes=")
	builder.WriteString(_m.AdminNotes)
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceVoidRequests is a parsable slice of InvoiceVoidRequest.
type InvoiceVoidRequests []*InvoiceVoidRequest
