// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralcommissionreleaselog"
)

// ReferralCommissionReleaseLog is the model entity for the ReferralCommissionReleaseLog schema.
type ReferralCommissionReleaseLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CommissionID holds the value of the "commission_id" field.
	CommissionID int64 `json:"commission_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// recharge_consumed | subscription_daily | manual_admin | refund_reversal
	TriggerType string `json:"trigger_type,omitempty"`
	// RateSnapshot holds the value of the "rate_snapshot" field.
	RateSnapshot float64 `json:"rate_snapshot,omitempty"`
	// ComputationDetail holds the value of the "computation_detail" field.
	ComputationDetail string `json:"computation_detail,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralCommissionReleaseLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralcommissionreleaselog.FieldAmount, referralcommissionreleaselog.FieldRateSnapshot:
			values[i] = new(sql.NullFloat64)
		case referralcommissionreleaselog.FieldID, referralcommissionreleaselog.FieldCommissionID, referralcommissionreleaselog.FieldUserID:
			values[i] = new(sql.NullInt64)
		case referralcommissionreleaselog.FieldTriggerType, referralcommissionreleaselog.FieldComputationDetail:
			values[i] = new(sql.NullString)
		case referralcommissionreleaselog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralCommissionReleaseLog fields.
func (_m *ReferralCommissionReleaseLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralcommissionreleaselog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralcommissionreleaselog.FieldCommissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_id", values[i])
			} else if value.Valid {
				_m.CommissionID = value.Int64
			}
		case referralcommissionreleaselog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case referralcommissionreleaselog.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case referralcommissionreleaselog.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = value.String
			}
		case referralcommissionreleaselog.FieldRateSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_snapshot", values[i])
			} else if value.Valid {
				_m.RateSnapshot = value.Float64
			}
		case referralcommissionreleaselog.FieldComputationDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field computation_detail", values[i])
			} else if value.Valid {
				_m.ComputationDetail = value.String
			}
		case referralcommissionreleaselog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralCommissionReleaseLog.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralCommissionReleaseLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralCommissionReleaseLog.
// Note that you need to call ReferralCommissionReleaseLog.Unwrap() before calling this method if this ReferralCommissionReleaseLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralCommissionReleaseLog) Update() *ReferralCommissionReleaseLogUpdateOne {
	return NewReferralCommissionReleaseLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralCommissionReleaseLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralCommissionReleaseLog) Unwrap() *ReferralCommissionReleaseLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralCommissionReleaseLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralCommissionReleaseLog) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralCommissionReleaseLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("commission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(_m.TriggerType)
	builder.WriteString(", ")
	builder.WriteString("rate_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateSnapshot))
	builder.WriteString(", ")
	builder.WriteString("computation_detail=")
	builder.WriteString(_m.ComputationDetail)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralCommissionReleaseLogs is a parsable slice of ReferralCommissionReleaseLog.
type ReferralCommissionReleaseLogs []*ReferralCommissionReleaseLog
