// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralpendingbonus"
)

// ReferralPendingBonus is the model entity for the ReferralPendingBonus schema.
type ReferralPendingBonus struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RefereeID holds the value of the "referee_id" field.
	RefereeID int64 `json:"referee_id,omitempty"`
	// ReferrerID holds the value of the "referrer_id" field.
	ReferrerID int64 `json:"referrer_id,omitempty"`
	// BonusAmount holds the value of the "bonus_amount" field.
	BonusAmount float64 `json:"bonus_amount,omitempty"`
	// pending | granted
	Status string `json:"status,omitempty"`
	// GrantedAt holds the value of the "granted_at" field.
	GrantedAt *time.Time `json:"granted_at,omitempty"`
	// first_recharge | first_subscription
	GrantedTrigger *string `json:"granted_trigger,omitempty"`
	// GrantedOrderID holds the value of the "granted_order_id" field.
	GrantedOrderID *int64 `json:"granted_order_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralPendingBonus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralpendingbonus.FieldBonusAmount:
			values[i] = new(sql.NullFloat64)
		case referralpendingbonus.FieldID, referralpendingbonus.FieldRefereeID, referralpendingbonus.FieldReferrerID, referralpendingbonus.FieldGrantedOrderID:
			values[i] = new(sql.NullInt64)
		case referralpendingbonus.FieldStatus, referralpendingbonus.FieldGrantedTrigger:
			values[i] = new(sql.NullString)
		case referralpendingbonus.FieldGrantedAt, referralpendingbonus.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralPendingBonus fields.
func (_m *ReferralPendingBonus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralpendingbonus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralpendingbonus.FieldRefereeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referee_id", values[i])
			} else if value.Valid {
				_m.RefereeID = value.Int64
			}
		case referralpendingbonus.FieldReferrerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_id", values[i])
			} else if value.Valid {
				_m.ReferrerID = value.Int64
			}
		case referralpendingbonus.FieldBonusAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_amount", values[i])
			} else if value.Valid {
				_m.BonusAmount = value.Float64
			}
		case referralpendingbonus.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case referralpendingbonus.FieldGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field granted_at", values[i])
			} else if value.Valid {
				_m.GrantedAt = new(time.Time)
				*_m.GrantedAt = value.Time
			}
		case referralpendingbonus.FieldGrantedTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field granted_trigger", values[i])
			} else if value.Valid {
				_m.GrantedTrigger = new(string)
				*_m.GrantedTrigger = value.String
			}
		case referralpendingbonus.FieldGrantedOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_order_id", values[i])
			} else if value.Valid {
				_m.GrantedOrderID = new(int64)
				*_m.GrantedOrderID = value.Int64
			}
		case referralpendingbonus.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralPendingBonus.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralPendingBonus) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralPendingBonus.
// Note that you need to call ReferralPendingBonus.Unwrap() before calling this method if this ReferralPendingBonus
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralPendingBonus) Update() *ReferralPendingBonusUpdateOne {
	return NewReferralPendingBonusClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralPendingBonus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralPendingBonus) Unwrap() *ReferralPendingBonus {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralPendingBonus is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralPendingBonus) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralPendingBonus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("referee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefereeID))
	builder.WriteString(", ")
	builder.WriteString("referrer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerID))
	builder.WriteString(", ")
	builder.WriteString("bonus_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.GrantedAt; v != nil {
		builder.WriteString("granted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.GrantedTrigger; v != nil {
		builder.WriteString("granted_trigger=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GrantedOrderID; v != nil {
		builder.WriteString("granted_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralPendingBonusSlice is a parsable slice of ReferralPendingBonus.
type ReferralPendingBonusSlice []*ReferralPendingBonus
