// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralcommissionreleaselog"
)

// ReferralCommissionReleaseLogCreate is the builder for creating a ReferralCommissionReleaseLog entity.
type ReferralCommissionReleaseLogCreate struct {
	config
	mutation *ReferralCommissionReleaseLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCommissionID sets the "commission_id" field.
func (_c *ReferralCommissionReleaseLogCreate) SetCommissionID(v int64) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetCommissionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ReferralCommissionReleaseLogCreate) SetUserID(v int64) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ReferralCommissionReleaseLogCreate) SetAmount(v float64) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetTriggerType sets the "trigger_type" field.
func (_c *ReferralCommissionReleaseLogCreate) SetTriggerType(v string) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetTriggerType(v)
	return _c
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (_c *ReferralCommissionReleaseLogCreate) SetRateSnapshot(v float64) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetRateSnapshot(v)
	return _c
}

// SetComputationDetail sets the "computation_detail" field.
func (_c *ReferralCommissionReleaseLogCreate) SetComputationDetail(v string) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetComputationDetail(v)
	return _c
}

// SetNillableComputationDetail sets the "computation_detail" field if the given value is not nil.
func (_c *ReferralCommissionReleaseLogCreate) SetNillableComputationDetail(v *string) *ReferralCommissionReleaseLogCreate {
	if v != nil {
		_c.SetComputationDetail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralCommissionReleaseLogCreate) SetCreatedAt(v time.Time) *ReferralCommissionReleaseLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralCommissionReleaseLogCreate) SetNillableCreatedAt(v *time.Time) *ReferralCommissionReleaseLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReferralCommissionReleaseLogMutation object of the builder.
func (_c *ReferralCommissionReleaseLogCreate) Mutation() *ReferralCommissionReleaseLogMutation {
	return _c.mutation
}

// Save creates the ReferralCommissionReleaseLog in the database.
func (_c *ReferralCommissionReleaseLogCreate) Save(ctx context.Context) (*ReferralCommissionReleaseLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralCommissionReleaseLogCreate) SaveX(ctx context.Context) *ReferralCommissionReleaseLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionReleaseLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionReleaseLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralCommissionReleaseLogCreate) defaults() {
	if _, ok := _c.mutation.ComputationDetail(); !ok {
		v := referralcommissionreleaselog.DefaultComputationDetail
		_c.mutation.SetComputationDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralcommissionreleaselog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralCommissionReleaseLogCreate) check() error {
	if _, ok := _c.mutation.CommissionID(); !ok {
		return &ValidationError{Name: "commission_id", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.commission_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.amount"`)}
	}
	if _, ok := _c.mutation.TriggerType(); !ok {
		return &ValidationError{Name: "trigger_type", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.trigger_type"`)}
	}
	if v, ok := _c.mutation.TriggerType(); ok {
		if err := referralcommissionreleaselog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "ReferralCommissionReleaseLog.trigger_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateSnapshot(); !ok {
		return &ValidationError{Name: "rate_snapshot", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.rate_snapshot"`)}
	}
	if _, ok := _c.mutation.ComputationDetail(); !ok {
		return &ValidationError{Name: "computation_detail", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.computation_detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralCommissionReleaseLog.created_at"`)}
	}
	return nil
}

func (_c *ReferralCommissionReleaseLogCreate) sqlSave(ctx context.Context) (*ReferralCommissionReleaseLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralCommissionReleaseLogCreate) createSpec() (*ReferralCommissionReleaseLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralCommissionReleaseLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralcommissionreleaselog.Table, sqlgraph.NewFieldSpec(referralcommissionreleaselog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CommissionID(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldCommissionID, field.TypeInt64, value)
		_node.CommissionID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.TriggerType(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldTriggerType, field.TypeString, value)
		_node.TriggerType = value
	}
	if value, ok := _c.mutation.RateSnapshot(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldRateSnapshot, field.TypeFloat64, value)
		_node.RateSnapshot = value
	}
	if value, ok := _c.mutation.ComputationDetail(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldComputationDetail, field.TypeString, value)
		_node.ComputationDetail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralcommissionreleaselog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommissionReleaseLog.Create().
//		SetCommissionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionReleaseLogUpsert) {
//			SetCommissionID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionReleaseLogCreate) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionReleaseLogUpsertOne {
	_c.conflict = opts
	return &ReferralCommissionReleaseLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommissionReleaseLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionReleaseLogCreate) OnConflictColumns(columns ...string) *ReferralCommissionReleaseLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionReleaseLogUpsertOne{
		create: _c,
	}
}

type (
	// ReferralCommissionReleaseLogUpsertOne is the builder for "upsert"-ing
	//  one ReferralCommissionReleaseLog node.
	ReferralCommissionReleaseLogUpsertOne struct {
		create *ReferralCommissionReleaseLogCreate
	}

	// ReferralCommissionReleaseLogUpsert is the "OnConflict" setter.
	ReferralCommissionReleaseLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetCommissionID sets the "commission_id" field.
func (u *ReferralCommissionReleaseLogUpsert) SetCommissionID(v int64) *ReferralCommissionReleaseLogUpsert {
	u.Set(referralcommissionreleaselog.FieldCommissionID, v)
	return u
}

// UpdateCommissionID sets the "commission_id" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsert) UpdateCommissionID() *ReferralCommissionReleaseLogUpsert {
	u.SetExcluded(referralcommissionreleaselog.FieldCommissionID)
	return u
}

// AddCommissionID adds v to the "commission_id" field.
func (u *ReferralCommissionReleaseLogUpsert) AddCommissionID(v int64) *ReferralCommissionReleaseLogUpsert {
	u.Add(referralcommissionreleaselog.FieldCommissionID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReferralCommissionReleaseLogUpsert) SetUserID(v int64) *ReferralCommissionReleaseLogUpsert {
	u.Set(referralcommissionreleaselog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsert) UpdateUserID() *ReferralCommissionReleaseLogUpsert {
	u.SetExcluded(referralcommissionreleaselog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ReferralCommissionReleaseLogUpsert) AddUserID(v int64) *ReferralCommissionReleaseLogUpsert {
	u.Add(referralcommissionreleaselog.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *ReferralCommissionReleaseLogUpsert) SetAmount(v float64) *ReferralCommissionReleaseLogUpsert {
	u.Set(referralcommissionreleaselog.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsert) UpdateAmount() *ReferralCommissionReleaseLogUpsert {
	u.SetExcluded(referralcommissionreleaselog.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ReferralCommissionReleaseLogUpsert) AddAmount(v float64) *ReferralCommissionReleaseLogUpsert {
	u.Add(referralcommissionreleaselog.FieldAmount, v)
	return u
}

// SetTriggerType sets the "trigger_type" field.
func (u *ReferralCommissionReleaseLogUpsert) SetTriggerType(v string) *ReferralCommissionReleaseLogUpsert {
	u.Set(referralcommissionreleaselog.FieldTriggerType, v)
	return u
}

// UpdateTriggerType sets the "trigger_type" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsert) UpdateTriggerType() *ReferralCommissionReleaseLogUpsert {
	u.SetExcluded(referralcommissionreleaselog.FieldTriggerType)
	return u
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (u *ReferralCommissionReleaseLogUpsert) SetRateSnapshot(v float64) *ReferralCommissionReleaseLogUpsert {
	u.Set(referralcommissionreleaselog.FieldRateSnapshot, v)
	return u
}

// UpdateRateSnapshot sets the "rate_snapshot" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsert) UpdateRateSnapshot() *ReferralCommissionReleaseLogUpsert {
	u.SetExcluded(referralcommissionreleaselog.FieldRateSnapshot)
	return u
}

// AddRateSnapshot adds v to the "rate_snapshot" field.
func (u *ReferralCommissionReleaseLogUpsert) AddRateSnapshot(v float64) *ReferralCommissionReleaseLogUpsert {
	u.Add(referralcommissionreleaselog.FieldRateSnapshot, v)
	return u
}

// SetComputationDetail sets the "computation_detail" field.
func (u *ReferralCommissionReleaseLogUpsert) SetComputationDetail(v string) *ReferralCommissionReleaseLogUpsert {
	u.Set(referralcommissionreleaselog.FieldComputationDetail, v)
	return u
}

// UpdateComputationDetail sets the "computation_detail" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsert) UpdateComputationDetail() *ReferralCommissionReleaseLogUpsert {
	u.SetExcluded(referralcommissionreleaselog.FieldComputationDetail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralCommissionReleaseLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateNewValues() *ReferralCommissionReleaseLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralcommissionreleaselog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommissionReleaseLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralCommissionReleaseLogUpsertOne) Ignore() *ReferralCommissionReleaseLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionReleaseLogUpsertOne) DoNothing() *ReferralCommissionReleaseLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionReleaseLogCreate.OnConflict
// documentation for more info.
func (u *ReferralCommissionReleaseLogUpsertOne) Update(set func(*ReferralCommissionReleaseLogUpsert)) *ReferralCommissionReleaseLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionReleaseLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCommissionID sets the "commission_id" field.
func (u *ReferralCommissionReleaseLogUpsertOne) SetCommissionID(v int64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetCommissionID(v)
	})
}

// AddCommissionID adds v to the "commission_id" field.
func (u *ReferralCommissionReleaseLogUpsertOne) AddCommissionID(v int64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddCommissionID(v)
	})
}

// UpdateCommissionID sets the "commission_id" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateCommissionID() *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateCommissionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ReferralCommissionReleaseLogUpsertOne) SetUserID(v int64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ReferralCommissionReleaseLogUpsertOne) AddUserID(v int64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateUserID() *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralCommissionReleaseLogUpsertOne) SetAmount(v float64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralCommissionReleaseLogUpsertOne) AddAmount(v float64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateAmount() *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateAmount()
	})
}

// SetTriggerType sets the "trigger_type" field.
func (u *ReferralCommissionReleaseLogUpsertOne) SetTriggerType(v string) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetTriggerType(v)
	})
}

// UpdateTriggerType sets the "trigger_type" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateTriggerType() *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateTriggerType()
	})
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (u *ReferralCommissionReleaseLogUpsertOne) SetRateSnapshot(v float64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetRateSnapshot(v)
	})
}

// AddRateSnapshot adds v to the "rate_snapshot" field.
func (u *ReferralCommissionReleaseLogUpsertOne) AddRateSnapshot(v float64) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddRateSnapshot(v)
	})
}

// UpdateRateSnapshot sets the "rate_snapshot" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateRateSnapshot() *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateRateSnapshot()
	})
}

// SetComputationDetail sets the "computation_detail" field.
func (u *ReferralCommissionReleaseLogUpsertOne) SetComputationDetail(v string) *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetComputationDetail(v)
	})
}

// UpdateComputationDetail sets the "computation_detail" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertOne) UpdateComputationDetail() *ReferralCommissionReleaseLogUpsertOne {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateComputationDetail()
	})
}

// Exec executes the query.
func (u *ReferralCommissionReleaseLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionReleaseLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionReleaseLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralCommissionReleaseLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralCommissionReleaseLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralCommissionReleaseLogCreateBulk is the builder for creating many ReferralCommissionReleaseLog entities in bulk.
type ReferralCommissionReleaseLogCreateBulk struct {
	config
	err      error
	builders []*ReferralCommissionReleaseLogCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralCommissionReleaseLog entities in the database.
func (_c *ReferralCommissionReleaseLogCreateBulk) Save(ctx context.Context) ([]*ReferralCommissionReleaseLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralCommissionReleaseLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralCommissionReleaseLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralCommissionReleaseLogCreateBulk) SaveX(ctx context.Context) []*ReferralCommissionReleaseLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionReleaseLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionReleaseLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommissionReleaseLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionReleaseLogUpsert) {
//			SetCommissionID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionReleaseLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionReleaseLogUpsertBulk {
	_c.conflict = opts
	return &ReferralCommissionReleaseLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommissionReleaseLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionReleaseLogCreateBulk) OnConflictColumns(columns ...string) *ReferralCommissionReleaseLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionReleaseLogUpsertBulk{
		create: _c,
	}
}

// ReferralCommissionReleaseLogUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralCommissionReleaseLog nodes.
type ReferralCommissionReleaseLogUpsertBulk struct {
	create *ReferralCommissionReleaseLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralCommissionReleaseLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateNewValues() *ReferralCommissionReleaseLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralcommissionreleaselog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommissionReleaseLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralCommissionReleaseLogUpsertBulk) Ignore() *ReferralCommissionReleaseLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionReleaseLogUpsertBulk) DoNothing() *ReferralCommissionReleaseLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionReleaseLogCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralCommissionReleaseLogUpsertBulk) Update(set func(*ReferralCommissionReleaseLogUpsert)) *ReferralCommissionReleaseLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionReleaseLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCommissionID sets the "commission_id" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) SetCommissionID(v int64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetCommissionID(v)
	})
}

// AddCommissionID adds v to the "commission_id" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) AddCommissionID(v int64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddCommissionID(v)
	})
}

// UpdateCommissionID sets the "commission_id" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateCommissionID() *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateCommissionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) SetUserID(v int64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) AddUserID(v int64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateUserID() *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) SetAmount(v float64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) AddAmount(v float64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateAmount() *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateAmount()
	})
}

// SetTriggerType sets the "trigger_type" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) SetTriggerType(v string) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetTriggerType(v)
	})
}

// UpdateTriggerType sets the "trigger_type" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateTriggerType() *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateTriggerType()
	})
}

// SetRateSnapshot sets the "rate_snapshot" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) SetRateSnapshot(v float64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetRateSnapshot(v)
	})
}

// AddRateSnapshot adds v to the "rate_snapshot" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) AddRateSnapshot(v float64) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.AddRateSnapshot(v)
	})
}

// UpdateRateSnapshot sets the "rate_snapshot" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateRateSnapshot() *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateRateSnapshot()
	})
}

// SetComputationDetail sets the "computation_detail" field.
func (u *ReferralCommissionReleaseLogUpsertBulk) SetComputationDetail(v string) *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.SetComputationDetail(v)
	})
}

// UpdateComputationDetail sets the "computation_detail" field to the value that was provided on create.
func (u *ReferralCommissionReleaseLogUpsertBulk) UpdateComputationDetail() *ReferralCommissionReleaseLogUpsertBulk {
	return u.Update(func(s *ReferralCommissionReleaseLogUpsert) {
		s.UpdateComputationDetail()
	})
}

// Exec executes the query.
func (u *ReferralCommissionReleaseLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralCommissionReleaseLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionReleaseLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionReleaseLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
