// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralwithdrawal"
)

// ReferralWithdrawalCreate is the builder for creating a ReferralWithdrawal entity.
type ReferralWithdrawalCreate struct {
	config
	mutation *ReferralWithdrawalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralWithdrawalCreate) SetCreatedAt(v time.Time) *ReferralWithdrawalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableCreatedAt(v *time.Time) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReferralWithdrawalCreate) SetUpdatedAt(v time.Time) *ReferralWithdrawalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableUpdatedAt(v *time.Time) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ReferralWithdrawalCreate) SetUserID(v int64) *ReferralWithdrawalCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ReferralWithdrawalCreate) SetAmount(v float64) *ReferralWithdrawalCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetPayoutMethod sets the "payout_method" field.
func (_c *ReferralWithdrawalCreate) SetPayoutMethod(v string) *ReferralWithdrawalCreate {
	_c.mutation.SetPayoutMethod(v)
	return _c
}

// SetPayoutAccount sets the "payout_account" field.
func (_c *ReferralWithdrawalCreate) SetPayoutAccount(v string) *ReferralWithdrawalCreate {
	_c.mutation.SetPayoutAccount(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ReferralWithdrawalCreate) SetNotes(v string) *ReferralWithdrawalCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableNotes(v *string) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReferralWithdrawalCreate) SetStatus(v string) *ReferralWithdrawalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableStatus(v *string) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *ReferralWithdrawalCreate) SetRequestedAt(v time.Time) *ReferralWithdrawalCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *ReferralWithdrawalCreate) SetReviewedAt(v time.Time) *ReferralWithdrawalCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableReviewedAt(v *time.Time) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ReferralWithdrawalCreate) SetCompletedAt(v time.Time) *ReferralWithdrawalCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableCompletedAt(v *time.Time) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *ReferralWithdrawalCreate) SetReviewedBy(v int64) *ReferralWithdrawalCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableReviewedBy(v *int64) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewNotes sets the "review_notes" field.
func (_c *ReferralWithdrawalCreate) SetReviewNotes(v string) *ReferralWithdrawalCreate {
	_c.mutation.SetReviewNotes(v)
	return _c
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_c *ReferralWithdrawalCreate) SetNillableReviewNotes(v *string) *ReferralWithdrawalCreate {
	if v != nil {
		_c.SetReviewNotes(*v)
	}
	return _c
}

// Mutation returns the ReferralWithdrawalMutation object of the builder.
func (_c *ReferralWithdrawalCreate) Mutation() *ReferralWithdrawalMutation {
	return _c.mutation
}

// Save creates the ReferralWithdrawal in the database.
func (_c *ReferralWithdrawalCreate) Save(ctx context.Context) (*ReferralWithdrawal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralWithdrawalCreate) SaveX(ctx context.Context) *ReferralWithdrawal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralWithdrawalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralWithdrawalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralWithdrawalCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralwithdrawal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := referralwithdrawal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := referralwithdrawal.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := referralwithdrawal.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ReviewNotes(); !ok {
		v := referralwithdrawal.DefaultReviewNotes
		_c.mutation.SetReviewNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralWithdrawalCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralWithdrawal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReferralWithdrawal.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ReferralWithdrawal.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ReferralWithdrawal.amount"`)}
	}
	if _, ok := _c.mutation.PayoutMethod(); !ok {
		return &ValidationError{Name: "payout_method", err: errors.New(`ent: missing required field "ReferralWithdrawal.payout_method"`)}
	}
	if v, ok := _c.mutation.PayoutMethod(); ok {
		if err := referralwithdrawal.PayoutMethodValidator(v); err != nil {
			return &ValidationError{Name: "payout_method", err: fmt.Errorf(`ent: validator failed for field "ReferralWithdrawal.payout_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayoutAccount(); !ok {
		return &ValidationError{Name: "payout_account", err: errors.New(`ent: missing required field "ReferralWithdrawal.payout_account"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "ReferralWithdrawal.notes"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReferralWithdrawal.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := referralwithdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralWithdrawal.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "ReferralWithdrawal.requested_at"`)}
	}
	if _, ok := _c.mutation.ReviewNotes(); !ok {
		return &ValidationError{Name: "review_notes", err: errors.New(`ent: missing required field "ReferralWithdrawal.review_notes"`)}
	}
	return nil
}

func (_c *ReferralWithdrawalCreate) sqlSave(ctx context.Context) (*ReferralWithdrawal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralWithdrawalCreate) createSpec() (*ReferralWithdrawal, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralWithdrawal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralwithdrawal.Table, sqlgraph.NewFieldSpec(referralwithdrawal.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralwithdrawal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(referralwithdrawal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(referralwithdrawal.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(referralwithdrawal.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.PayoutMethod(); ok {
		_spec.SetField(referralwithdrawal.FieldPayoutMethod, field.TypeString, value)
		_node.PayoutMethod = value
	}
	if value, ok := _c.mutation.PayoutAccount(); ok {
		_spec.SetField(referralwithdrawal.FieldPayoutAccount, field.TypeString, value)
		_node.PayoutAccount = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(referralwithdrawal.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(referralwithdrawal.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(referralwithdrawal.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(referralwithdrawal.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(referralwithdrawal.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(referralwithdrawal.FieldReviewedBy, field.TypeInt64, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.ReviewNotes(); ok {
		_spec.SetField(referralwithdrawal.FieldReviewNotes, field.TypeString, value)
		_node.ReviewNotes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralWithdrawal.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralWithdrawalUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralWithdrawalCreate) OnConflict(opts ...sql.ConflictOption) *ReferralWithdrawalUpsertOne {
	_c.conflict = opts
	return &ReferralWithdrawalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralWithdrawal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralWithdrawalCreate) OnConflictColumns(columns ...string) *ReferralWithdrawalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralWithdrawalUpsertOne{
		create: _c,
	}
}

type (
	// ReferralWithdrawalUpsertOne is the builder for "upsert"-ing
	//  one ReferralWithdrawal node.
	ReferralWithdrawalUpsertOne struct {
		create *ReferralWithdrawalCreate
	}

	// ReferralWithdrawalUpsert is the "OnConflict" setter.
	ReferralWithdrawalUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralWithdrawalUpsert) SetUpdatedAt(v time.Time) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateUpdatedAt() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReferralWithdrawalUpsert) SetUserID(v int64) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateUserID() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ReferralWithdrawalUpsert) AddUserID(v int64) *ReferralWithdrawalUpsert {
	u.Add(referralwithdrawal.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *ReferralWithdrawalUpsert) SetAmount(v float64) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateAmount() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ReferralWithdrawalUpsert) AddAmount(v float64) *ReferralWithdrawalUpsert {
	u.Add(referralwithdrawal.FieldAmount, v)
	return u
}

// SetPayoutMethod sets the "payout_method" field.
func (u *ReferralWithdrawalUpsert) SetPayoutMethod(v string) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldPayoutMethod, v)
	return u
}

// UpdatePayoutMethod sets the "payout_method" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdatePayoutMethod() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldPayoutMethod)
	return u
}

// SetPayoutAccount sets the "payout_account" field.
func (u *ReferralWithdrawalUpsert) SetPayoutAccount(v string) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldPayoutAccount, v)
	return u
}

// UpdatePayoutAccount sets the "payout_account" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdatePayoutAccount() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldPayoutAccount)
	return u
}

// SetNotes sets the "notes" field.
func (u *ReferralWithdrawalUpsert) SetNotes(v string) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateNotes() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldNotes)
	return u
}

// SetStatus sets the "status" field.
func (u *ReferralWithdrawalUpsert) SetStatus(v string) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateStatus() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldStatus)
	return u
}

// SetRequestedAt sets the "requested_at" field.
func (u *ReferralWithdrawalUpsert) SetRequestedAt(v time.Time) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldRequestedAt, v)
	return u
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateRequestedAt() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldRequestedAt)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *ReferralWithdrawalUpsert) SetReviewedAt(v time.Time) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateReviewedAt() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *ReferralWithdrawalUpsert) ClearReviewedAt() *ReferralWithdrawalUpsert {
	u.SetNull(referralwithdrawal.FieldReviewedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ReferralWithdrawalUpsert) SetCompletedAt(v time.Time) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateCompletedAt() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ReferralWithdrawalUpsert) ClearCompletedAt() *ReferralWithdrawalUpsert {
	u.SetNull(referralwithdrawal.FieldCompletedAt)
	return u
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *ReferralWithdrawalUpsert) SetReviewedBy(v int64) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldReviewedBy, v)
	return u
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateReviewedBy() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldReviewedBy)
	return u
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *ReferralWithdrawalUpsert) AddReviewedBy(v int64) *ReferralWithdrawalUpsert {
	u.Add(referralwithdrawal.FieldReviewedBy, v)
	return u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *ReferralWithdrawalUpsert) ClearReviewedBy() *ReferralWithdrawalUpsert {
	u.SetNull(referralwithdrawal.FieldReviewedBy)
	return u
}

// SetReviewNotes sets the "review_notes" field.
func (u *ReferralWithdrawalUpsert) SetReviewNotes(v string) *ReferralWithdrawalUpsert {
	u.Set(referralwithdrawal.FieldReviewNotes, v)
	return u
}

// UpdateReviewNotes sets the "review_notes" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsert) UpdateReviewNotes() *ReferralWithdrawalUpsert {
	u.SetExcluded(referralwithdrawal.FieldReviewNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralWithdrawal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralWithdrawalUpsertOne) UpdateNewValues() *ReferralWithdrawalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralwithdrawal.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralWithdrawal.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralWithdrawalUpsertOne) Ignore() *ReferralWithdrawalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralWithdrawalUpsertOne) DoNothing() *ReferralWithdrawalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralWithdrawalCreate.OnConflict
// documentation for more info.
func (u *ReferralWithdrawalUpsertOne) Update(set func(*ReferralWithdrawalUpsert)) *ReferralWithdrawalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralWithdrawalUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralWithdrawalUpsertOne) SetUpdatedAt(v time.Time) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateUpdatedAt() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ReferralWithdrawalUpsertOne) SetUserID(v int64) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ReferralWithdrawalUpsertOne) AddUserID(v int64) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateUserID() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralWithdrawalUpsertOne) SetAmount(v float64) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralWithdrawalUpsertOne) AddAmount(v float64) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateAmount() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateAmount()
	})
}

// SetPayoutMethod sets the "payout_method" field.
func (u *ReferralWithdrawalUpsertOne) SetPayoutMethod(v string) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetPayoutMethod(v)
	})
}

// UpdatePayoutMethod sets the "payout_method" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdatePayoutMethod() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdatePayoutMethod()
	})
}

// SetPayoutAccount sets the "payout_account" field.
func (u *ReferralWithdrawalUpsertOne) SetPayoutAccount(v string) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetPayoutAccount(v)
	})
}

// UpdatePayoutAccount sets the "payout_account" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdatePayoutAccount() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdatePayoutAccount()
	})
}

// SetNotes sets the "notes" field.
func (u *ReferralWithdrawalUpsertOne) SetNotes(v string) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateNotes() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateNotes()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralWithdrawalUpsertOne) SetStatus(v string) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateStatus() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *ReferralWithdrawalUpsertOne) SetRequestedAt(v time.Time) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateRequestedAt() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *ReferralWithdrawalUpsertOne) SetReviewedAt(v time.Time) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateReviewedAt() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *ReferralWithdrawalUpsertOne) ClearReviewedAt() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.ClearReviewedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ReferralWithdrawalUpsertOne) SetCompletedAt(v time.Time) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateCompletedAt() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ReferralWithdrawalUpsertOne) ClearCompletedAt() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.ClearCompletedAt()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *ReferralWithdrawalUpsertOne) SetReviewedBy(v int64) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *ReferralWithdrawalUpsertOne) AddReviewedBy(v int64) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateReviewedBy() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *ReferralWithdrawalUpsertOne) ClearReviewedBy() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewNotes sets the "review_notes" field.
func (u *ReferralWithdrawalUpsertOne) SetReviewNotes(v string) *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetReviewNotes(v)
	})
}

// UpdateReviewNotes sets the "review_notes" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertOne) UpdateReviewNotes() *ReferralWithdrawalUpsertOne {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateReviewNotes()
	})
}

// Exec executes the query.
func (u *ReferralWithdrawalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralWithdrawalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralWithdrawalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralWithdrawalUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralWithdrawalUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralWithdrawalCreateBulk is the builder for creating many ReferralWithdrawal entities in bulk.
type ReferralWithdrawalCreateBulk struct {
	config
	err      error
	builders []*ReferralWithdrawalCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralWithdrawal entities in the database.
func (_c *ReferralWithdrawalCreateBulk) Save(ctx context.Context) ([]*ReferralWithdrawal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralWithdrawal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralWithdrawalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralWithdrawalCreateBulk) SaveX(ctx context.Context) []*ReferralWithdrawal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralWithdrawalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralWithdrawalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralWithdrawal.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralWithdrawalUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralWithdrawalCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralWithdrawalUpsertBulk {
	_c.conflict = opts
	return &ReferralWithdrawalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralWithdrawal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralWithdrawalCreateBulk) OnConflictColumns(columns ...string) *ReferralWithdrawalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralWithdrawalUpsertBulk{
		create: _c,
	}
}

// ReferralWithdrawalUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralWithdrawal nodes.
type ReferralWithdrawalUpsertBulk struct {
	create *ReferralWithdrawalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralWithdrawal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralWithdrawalUpsertBulk) UpdateNewValues() *ReferralWithdrawalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralwithdrawal.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralWithdrawal.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralWithdrawalUpsertBulk) Ignore() *ReferralWithdrawalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralWithdrawalUpsertBulk) DoNothing() *ReferralWithdrawalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralWithdrawalCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralWithdrawalUpsertBulk) Update(set func(*ReferralWithdrawalUpsert)) *ReferralWithdrawalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralWithdrawalUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReferralWithdrawalUpsertBulk) SetUpdatedAt(v time.Time) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateUpdatedAt() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ReferralWithdrawalUpsertBulk) SetUserID(v int64) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ReferralWithdrawalUpsertBulk) AddUserID(v int64) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateUserID() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *ReferralWithdrawalUpsertBulk) SetAmount(v float64) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReferralWithdrawalUpsertBulk) AddAmount(v float64) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateAmount() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateAmount()
	})
}

// SetPayoutMethod sets the "payout_method" field.
func (u *ReferralWithdrawalUpsertBulk) SetPayoutMethod(v string) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetPayoutMethod(v)
	})
}

// UpdatePayoutMethod sets the "payout_method" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdatePayoutMethod() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdatePayoutMethod()
	})
}

// SetPayoutAccount sets the "payout_account" field.
func (u *ReferralWithdrawalUpsertBulk) SetPayoutAccount(v string) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetPayoutAccount(v)
	})
}

// UpdatePayoutAccount sets the "payout_account" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdatePayoutAccount() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdatePayoutAccount()
	})
}

// SetNotes sets the "notes" field.
func (u *ReferralWithdrawalUpsertBulk) SetNotes(v string) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateNotes() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateNotes()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralWithdrawalUpsertBulk) SetStatus(v string) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateStatus() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *ReferralWithdrawalUpsertBulk) SetRequestedAt(v time.Time) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateRequestedAt() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *ReferralWithdrawalUpsertBulk) SetReviewedAt(v time.Time) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateReviewedAt() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *ReferralWithdrawalUpsertBulk) ClearReviewedAt() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.ClearReviewedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ReferralWithdrawalUpsertBulk) SetCompletedAt(v time.Time) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateCompletedAt() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ReferralWithdrawalUpsertBulk) ClearCompletedAt() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.ClearCompletedAt()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *ReferralWithdrawalUpsertBulk) SetReviewedBy(v int64) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *ReferralWithdrawalUpsertBulk) AddReviewedBy(v int64) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateReviewedBy() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *ReferralWithdrawalUpsertBulk) ClearReviewedBy() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewNotes sets the "review_notes" field.
func (u *ReferralWithdrawalUpsertBulk) SetReviewNotes(v string) *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.SetReviewNotes(v)
	})
}

// UpdateReviewNotes sets the "review_notes" field to the value that was provided on create.
func (u *ReferralWithdrawalUpsertBulk) UpdateReviewNotes() *ReferralWithdrawalUpsertBulk {
	return u.Update(func(s *ReferralWithdrawalUpsert) {
		s.UpdateReviewNotes()
	})
}

// Exec executes the query.
func (u *ReferralWithdrawalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralWithdrawalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralWithdrawalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralWithdrawalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
