// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/refundrequest"
)

// RefundRequestUpdate is the builder for updating RefundRequest entities.
type RefundRequestUpdate struct {
	config
	hooks    []Hook
	mutation *RefundRequestMutation
}

// Where appends a list predicates to the RefundRequestUpdate builder.
func (_u *RefundRequestUpdate) Where(ps ...predicate.RefundRequest) *RefundRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefundRequestUpdate) SetUpdatedAt(v time.Time) *RefundRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RefundRequestUpdate) SetUserID(v int64) *RefundRequestUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableUserID(v *int64) *RefundRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RefundRequestUpdate) AddUserID(v int64) *RefundRequestUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *RefundRequestUpdate) SetPaymentOrderID(v string) *RefundRequestUpdate {
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillablePaymentOrderID(v *string) *RefundRequestUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// SetInvoiceID sets the "invoice_id" field.
func (_u *RefundRequestUpdate) SetInvoiceID(v int64) *RefundRequestUpdate {
	_u.mutation.ResetInvoiceID()
	_u.mutation.SetInvoiceID(v)
	return _u
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableInvoiceID(v *int64) *RefundRequestUpdate {
	if v != nil {
		_u.SetInvoiceID(*v)
	}
	return _u
}

// AddInvoiceID adds value to the "invoice_id" field.
func (_u *RefundRequestUpdate) AddInvoiceID(v int64) *RefundRequestUpdate {
	_u.mutation.AddInvoiceID(v)
	return _u
}

// ClearInvoiceID clears the value of the "invoice_id" field.
func (_u *RefundRequestUpdate) ClearInvoiceID() *RefundRequestUpdate {
	_u.mutation.ClearInvoiceID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RefundRequestUpdate) SetStatus(v string) *RefundRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableStatus(v *string) *RefundRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *RefundRequestUpdate) SetReason(v string) *RefundRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableReason(v *string) *RefundRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RefundRequestUpdate) SetAmount(v float64) *RefundRequestUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableAmount(v *float64) *RefundRequestUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RefundRequestUpdate) AddAmount(v float64) *RefundRequestUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *RefundRequestUpdate) SetAdminID(v int64) *RefundRequestUpdate {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableAdminID(v *int64) *RefundRequestUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *RefundRequestUpdate) AddAdminID(v int64) *RefundRequestUpdate {
	_u.mutation.AddAdminID(v)
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *RefundRequestUpdate) ClearAdminID() *RefundRequestUpdate {
	_u.mutation.ClearAdminID()
	return _u
}

// SetAdminNotes sets the "admin_notes" field.
func (_u *RefundRequestUpdate) SetAdminNotes(v string) *RefundRequestUpdate {
	_u.mutation.SetAdminNotes(v)
	return _u
}

// SetNillableAdminNotes sets the "admin_notes" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableAdminNotes(v *string) *RefundRequestUpdate {
	if v != nil {
		_u.SetAdminNotes(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *RefundRequestUpdate) SetLastError(v string) *RefundRequestUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *RefundRequestUpdate) SetNillableLastError(v *string) *RefundRequestUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the RefundRequestMutation object of the builder.
func (_u *RefundRequestUpdate) Mutation() *RefundRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefundRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefundRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefundRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefundRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefundRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refundrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefundRequestUpdate) check() error {
	if v, ok := _u.mutation.PaymentOrderID(); ok {
		if err := refundrequest.PaymentOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_order_id", err: fmt.Errorf(`ent: validator failed for field "RefundRequest.payment_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := refundrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RefundRequest.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RefundRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refundrequest.Table, refundrequest.Columns, sqlgraph.NewFieldSpec(refundrequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refundrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(refundrequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(refundrequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(refundrequest.FieldPaymentOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceID(); ok {
		_spec.SetField(refundrequest.FieldInvoiceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceID(); ok {
		_spec.AddField(refundrequest.FieldInvoiceID, field.TypeInt64, value)
	}
	if _u.mutation.InvoiceIDCleared() {
		_spec.ClearField(refundrequest.FieldInvoiceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(refundrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(refundrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(refundrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(refundrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(refundrequest.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(refundrequest.FieldAdminID, field.TypeInt64, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(refundrequest.FieldAdminID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminNotes(); ok {
		_spec.SetField(refundrequest.FieldAdminNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(refundrequest.FieldLastError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refundrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefundRequestUpdateOne is the builder for updating a single RefundRequest entity.
type RefundRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefundRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefundRequestUpdateOne) SetUpdatedAt(v time.Time) *RefundRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RefundRequestUpdateOne) SetUserID(v int64) *RefundRequestUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableUserID(v *int64) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RefundRequestUpdateOne) AddUserID(v int64) *RefundRequestUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *RefundRequestUpdateOne) SetPaymentOrderID(v string) *RefundRequestUpdateOne {
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillablePaymentOrderID(v *string) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// SetInvoiceID sets the "invoice_id" field.
func (_u *RefundRequestUpdateOne) SetInvoiceID(v int64) *RefundRequestUpdateOne {
	_u.mutation.ResetInvoiceID()
	_u.mutation.SetInvoiceID(v)
	return _u
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableInvoiceID(v *int64) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceID(*v)
	}
	return _u
}

// AddInvoiceID adds value to the "invoice_id" field.
func (_u *RefundRequestUpdateOne) AddInvoiceID(v int64) *RefundRequestUpdateOne {
	_u.mutation.AddInvoiceID(v)
	return _u
}

// ClearInvoiceID clears the value of the "invoice_id" field.
func (_u *RefundRequestUpdateOne) ClearInvoiceID() *RefundRequestUpdateOne {
	_u.mutation.ClearInvoiceID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RefundRequestUpdateOne) SetStatus(v string) *RefundRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableStatus(v *string) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *RefundRequestUpdateOne) SetReason(v string) *RefundRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableReason(v *string) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RefundRequestUpdateOne) SetAmount(v float64) *RefundRequestUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableAmount(v *float64) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RefundRequestUpdateOne) AddAmount(v float64) *RefundRequestUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *RefundRequestUpdateOne) SetAdminID(v int64) *RefundRequestUpdateOne {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableAdminID(v *int64) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *RefundRequestUpdateOne) AddAdminID(v int64) *RefundRequestUpdateOne {
	_u.mutation.AddAdminID(v)
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *RefundRequestUpdateOne) ClearAdminID() *RefundRequestUpdateOne {
	_u.mutation.ClearAdminID()
	return _u
}

// SetAdminNotes sets the "admin_notes" field.
func (_u *RefundRequestUpdateOne) SetAdminNotes(v string) *RefundRequestUpdateOne {
	_u.mutation.SetAdminNotes(v)
	return _u
}

// SetNillableAdminNotes sets the "admin_notes" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableAdminNotes(v *string) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetAdminNotes(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *RefundRequestUpdateOne) SetLastError(v string) *RefundRequestUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *RefundRequestUpdateOne) SetNillableLastError(v *string) *RefundRequestUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the RefundRequestMutation object of the builder.
func (_u *RefundRequestUpdateOne) Mutation() *RefundRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the RefundRequestUpdate builder.
func (_u *RefundRequestUpdateOne) Where(ps ...predicate.RefundRequest) *RefundRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RefundRequestUpdateOne) Select(field string, fields ...string) *RefundRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RefundRequest entity.
func (_u *RefundRequestUpdateOne) Save(ctx context.Context) (*RefundRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefundRequestUpdateOne) SaveX(ctx context.Context) *RefundRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RefundRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefundRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefundRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refundrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefundRequestUpdateOne) check() error {
	if v, ok := _u.mutation.PaymentOrderID(); ok {
		if err := refundrequest.PaymentOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_order_id", err: fmt.Errorf(`ent: validator failed for field "RefundRequest.payment_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := refundrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RefundRequest.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RefundRequestUpdateOne) sqlSave(ctx context.Context) (_node *RefundRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refundrequest.Table, refundrequest.Columns, sqlgraph.NewFieldSpec(refundrequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefundRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refundrequest.FieldID)
		for _, f := range fields {
			if !refundrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refundrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refundrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(refundrequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(refundrequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(refundrequest.FieldPaymentOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceID(); ok {
		_spec.SetField(refundrequest.FieldInvoiceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceID(); ok {
		_spec.AddField(refundrequest.FieldInvoiceID, field.TypeInt64, value)
	}
	if _u.mutation.InvoiceIDCleared() {
		_spec.ClearField(refundrequest.FieldInvoiceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(refundrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(refundrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(refundrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(refundrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(refundrequest.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(refundrequest.FieldAdminID, field.TypeInt64, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(refundrequest.FieldAdminID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminNotes(); ok {
		_spec.SetField(refundrequest.FieldAdminNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(refundrequest.FieldLastError, field.TypeString, value)
	}
	_node = &RefundRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refundrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
