// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/userreferralconfig"
)

// UserReferralConfigDelete is the builder for deleting a UserReferralConfig entity.
type UserReferralConfigDelete struct {
	config
	hooks    []Hook
	mutation *UserReferralConfigMutation
}

// Where appends a list predicates to the UserReferralConfigDelete builder.
func (_d *UserReferralConfigDelete) Where(ps ...predicate.UserReferralConfig) *UserReferralConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserReferralConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserReferralConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserReferralConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userreferralconfig.Table, sqlgraph.NewFieldSpec(userreferralconfig.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserReferralConfigDeleteOne is the builder for deleting a single UserReferralConfig entity.
type UserReferralConfigDeleteOne struct {
	_d *UserReferralConfigDelete
}

// Where appends a list predicates to the UserReferralConfigDelete builder.
func (_d *UserReferralConfigDeleteOne) Where(ps ...predicate.UserReferralConfig) *UserReferralConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserReferralConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userreferralconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserReferralConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
