// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/userreferralconfig"
)

// UserReferralConfigUpdate is the builder for updating UserReferralConfig entities.
type UserReferralConfigUpdate struct {
	config
	hooks    []Hook
	mutation *UserReferralConfigMutation
}

// Where appends a list predicates to the UserReferralConfigUpdate builder.
func (_u *UserReferralConfigUpdate) Where(ps ...predicate.UserReferralConfig) *UserReferralConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserReferralConfigUpdate) SetUpdatedAt(v time.Time) *UserReferralConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserReferralConfigUpdate) SetUserID(v int64) *UserReferralConfigUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserReferralConfigUpdate) SetNillableUserID(v *int64) *UserReferralConfigUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserReferralConfigUpdate) AddUserID(v int64) *UserReferralConfigUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserReferralConfigUpdate) SetEnabled(v bool) *UserReferralConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserReferralConfigUpdate) SetNillableEnabled(v *bool) *UserReferralConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// ClearEnabled clears the value of the "enabled" field.
func (_u *UserReferralConfigUpdate) ClearEnabled() *UserReferralConfigUpdate {
	_u.mutation.ClearEnabled()
	return _u
}

// SetCommissionRateOverride sets the "commission_rate_override" field.
func (_u *UserReferralConfigUpdate) SetCommissionRateOverride(v float64) *UserReferralConfigUpdate {
	_u.mutation.ResetCommissionRateOverride()
	_u.mutation.SetCommissionRateOverride(v)
	return _u
}

// SetNillableCommissionRateOverride sets the "commission_rate_override" field if the given value is not nil.
func (_u *UserReferralConfigUpdate) SetNillableCommissionRateOverride(v *float64) *UserReferralConfigUpdate {
	if v != nil {
		_u.SetCommissionRateOverride(*v)
	}
	return _u
}

// AddCommissionRateOverride adds value to the "commission_rate_override" field.
func (_u *UserReferralConfigUpdate) AddCommissionRateOverride(v float64) *UserReferralConfigUpdate {
	_u.mutation.AddCommissionRateOverride(v)
	return _u
}

// ClearCommissionRateOverride clears the value of the "commission_rate_override" field.
func (_u *UserReferralConfigUpdate) ClearCommissionRateOverride() *UserReferralConfigUpdate {
	_u.mutation.ClearCommissionRateOverride()
	return _u
}

// SetRefereeBonusOverride sets the "referee_bonus_override" field.
func (_u *UserReferralConfigUpdate) SetRefereeBonusOverride(v float64) *UserReferralConfigUpdate {
	_u.mutation.ResetRefereeBonusOverride()
	_u.mutation.SetRefereeBonusOverride(v)
	return _u
}

// SetNillableRefereeBonusOverride sets the "referee_bonus_override" field if the given value is not nil.
func (_u *UserReferralConfigUpdate) SetNillableRefereeBonusOverride(v *float64) *UserReferralConfigUpdate {
	if v != nil {
		_u.SetRefereeBonusOverride(*v)
	}
	return _u
}

// AddRefereeBonusOverride adds value to the "referee_bonus_override" field.
func (_u *UserReferralConfigUpdate) AddRefereeBonusOverride(v float64) *UserReferralConfigUpdate {
	_u.mutation.AddRefereeBonusOverride(v)
	return _u
}

// ClearRefereeBonusOverride clears the value of the "referee_bonus_override" field.
func (_u *UserReferralConfigUpdate) ClearRefereeBonusOverride() *UserReferralConfigUpdate {
	_u.mutation.ClearRefereeBonusOverride()
	return _u
}

// SetWithdrawalAllowed sets the "withdrawal_allowed" field.
func (_u *UserReferralConfigUpdate) SetWithdrawalAllowed(v bool) *UserReferralConfigUpdate {
	_u.mutation.SetWithdrawalAllowed(v)
	return _u
}

// SetNillableWithdrawalAllowed sets the "withdrawal_allowed" field if the given value is not nil.
func (_u *UserReferralConfigUpdate) SetNillableWithdrawalAllowed(v *bool) *UserReferralConfigUpdate {
	if v != nil {
		_u.SetWithdrawalAllowed(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserReferralConfigUpdate) SetNotes(v string) *UserReferralConfigUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserReferralConfigUpdate) SetNillableNotes(v *string) *UserReferralConfigUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// Mutation returns the UserReferralConfigMutation object of the builder.
func (_u *UserReferralConfigUpdate) Mutation() *UserReferralConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserReferralConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserReferralConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserReferralConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserReferralConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserReferralConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userreferralconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserReferralConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userreferralconfig.Table, userreferralconfig.Columns, sqlgraph.NewFieldSpec(userreferralconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userreferralconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userreferralconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userreferralconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(userreferralconfig.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.EnabledCleared() {
		_spec.ClearField(userreferralconfig.FieldEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.CommissionRateOverride(); ok {
		_spec.SetField(userreferralconfig.FieldCommissionRateOverride, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRateOverride(); ok {
		_spec.AddField(userreferralconfig.FieldCommissionRateOverride, field.TypeFloat64, value)
	}
	if _u.mutation.CommissionRateOverrideCleared() {
		_spec.ClearField(userreferralconfig.FieldCommissionRateOverride, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RefereeBonusOverride(); ok {
		_spec.SetField(userreferralconfig.FieldRefereeBonusOverride, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefereeBonusOverride(); ok {
		_spec.AddField(userreferralconfig.FieldRefereeBonusOverride, field.TypeFloat64, value)
	}
	if _u.mutation.RefereeBonusOverrideCleared() {
		_spec.ClearField(userreferralconfig.FieldRefereeBonusOverride, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WithdrawalAllowed(); ok {
		_spec.SetField(userreferralconfig.FieldWithdrawalAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userreferralconfig.FieldNotes, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userreferralconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserReferralConfigUpdateOne is the builder for updating a single UserReferralConfig entity.
type UserReferralConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserReferralConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserReferralConfigUpdateOne) SetUpdatedAt(v time.Time) *UserReferralConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserReferralConfigUpdateOne) SetUserID(v int64) *UserReferralConfigUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserReferralConfigUpdateOne) SetNillableUserID(v *int64) *UserReferralConfigUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserReferralConfigUpdateOne) AddUserID(v int64) *UserReferralConfigUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserReferralConfigUpdateOne) SetEnabled(v bool) *UserReferralConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserReferralConfigUpdateOne) SetNillableEnabled(v *bool) *UserReferralConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// ClearEnabled clears the value of the "enabled" field.
func (_u *UserReferralConfigUpdateOne) ClearEnabled() *UserReferralConfigUpdateOne {
	_u.mutation.ClearEnabled()
	return _u
}

// SetCommissionRateOverride sets the "commission_rate_override" field.
func (_u *UserReferralConfigUpdateOne) SetCommissionRateOverride(v float64) *UserReferralConfigUpdateOne {
	_u.mutation.ResetCommissionRateOverride()
	_u.mutation.SetCommissionRateOverride(v)
	return _u
}

// SetNillableCommissionRateOverride sets the "commission_rate_override" field if the given value is not nil.
func (_u *UserReferralConfigUpdateOne) SetNillableCommissionRateOverride(v *float64) *UserReferralConfigUpdateOne {
	if v != nil {
		_u.SetCommissionRateOverride(*v)
	}
	return _u
}

// AddCommissionRateOverride adds value to the "commission_rate_override" field.
func (_u *UserReferralConfigUpdateOne) AddCommissionRateOverride(v float64) *UserReferralConfigUpdateOne {
	_u.mutation.AddCommissionRateOverride(v)
	return _u
}

// ClearCommissionRateOverride clears the value of the "commission_rate_override" field.
func (_u *UserReferralConfigUpdateOne) ClearCommissionRateOverride() *UserReferralConfigUpdateOne {
	_u.mutation.ClearCommissionRateOverride()
	return _u
}

// SetRefereeBonusOverride sets the "referee_bonus_override" field.
func (_u *UserReferralConfigUpdateOne) SetRefereeBonusOverride(v float64) *UserReferralConfigUpdateOne {
	_u.mutation.ResetRefereeBonusOverride()
	_u.mutation.SetRefereeBonusOverride(v)
	return _u
}

// SetNillableRefereeBonusOverride sets the "referee_bonus_override" field if the given value is not nil.
func (_u *UserReferralConfigUpdateOne) SetNillableRefereeBonusOverride(v *float64) *UserReferralConfigUpdateOne {
	if v != nil {
		_u.SetRefereeBonusOverride(*v)
	}
	return _u
}

// AddRefereeBonusOverride adds value to the "referee_bonus_override" field.
func (_u *UserReferralConfigUpdateOne) AddRefereeBonusOverride(v float64) *UserReferralConfigUpdateOne {
	_u.mutation.AddRefereeBonusOverride(v)
	return _u
}

// ClearRefereeBonusOverride clears the value of the "referee_bonus_override" field.
func (_u *UserReferralConfigUpdateOne) ClearRefereeBonusOverride() *UserReferralConfigUpdateOne {
	_u.mutation.ClearRefereeBonusOverride()
	return _u
}

// SetWithdrawalAllowed sets the "withdrawal_allowed" field.
func (_u *UserReferralConfigUpdateOne) SetWithdrawalAllowed(v bool) *UserReferralConfigUpdateOne {
	_u.mutation.SetWithdrawalAllowed(v)
	return _u
}

// SetNillableWithdrawalAllowed sets the "withdrawal_allowed" field if the given value is not nil.
func (_u *UserReferralConfigUpdateOne) SetNillableWithdrawalAllowed(v *bool) *UserReferralConfigUpdateOne {
	if v != nil {
		_u.SetWithdrawalAllowed(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserReferralConfigUpdateOne) SetNotes(v string) *UserReferralConfigUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserReferralConfigUpdateOne) SetNillableNotes(v *string) *UserReferralConfigUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// Mutation returns the UserReferralConfigMutation object of the builder.
func (_u *UserReferralConfigUpdateOne) Mutation() *UserReferralConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserReferralConfigUpdate builder.
func (_u *UserReferralConfigUpdateOne) Where(ps ...predicate.UserReferralConfig) *UserReferralConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserReferralConfigUpdateOne) Select(field string, fields ...string) *UserReferralConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserReferralConfig entity.
func (_u *UserReferralConfigUpdateOne) Save(ctx context.Context) (*UserReferralConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserReferralConfigUpdateOne) SaveX(ctx context.Context) *UserReferralConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserReferralConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserReferralConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserReferralConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userreferralconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserReferralConfigUpdateOne) sqlSave(ctx context.Context) (_node *UserReferralConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(userreferralconfig.Table, userreferralconfig.Columns, sqlgraph.NewFieldSpec(userreferralconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserReferralConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userreferralconfig.FieldID)
		for _, f := range fields {
			if !userreferralconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userreferralconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userreferralconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userreferralconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userreferralconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(userreferralconfig.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.EnabledCleared() {
		_spec.ClearField(userreferralconfig.FieldEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.CommissionRateOverride(); ok {
		_spec.SetField(userreferralconfig.FieldCommissionRateOverride, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRateOverride(); ok {
		_spec.AddField(userreferralconfig.FieldCommissionRateOverride, field.TypeFloat64, value)
	}
	if _u.mutation.CommissionRateOverrideCleared() {
		_spec.ClearField(userreferralconfig.FieldCommissionRateOverride, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RefereeBonusOverride(); ok {
		_spec.SetField(userreferralconfig.FieldRefereeBonusOverride, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefereeBonusOverride(); ok {
		_spec.AddField(userreferralconfig.FieldRefereeBonusOverride, field.TypeFloat64, value)
	}
	if _u.mutation.RefereeBonusOverrideCleared() {
		_spec.ClearField(userreferralconfig.FieldRefereeBonusOverride, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WithdrawalAllowed(); ok {
		_spec.SetField(userreferralconfig.FieldWithdrawalAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userreferralconfig.FieldNotes, field.TypeString, value)
	}
	_node = &UserReferralConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userreferralconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
