// Code generated by ent, DO NOT EDIT.

package referralpendingbonus

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the referralpendingbonus type in the database.
	Label = "referral_pending_bonus"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefereeID holds the string denoting the referee_id field in the database.
	FieldRefereeID = "referee_id"
	// FieldReferrerID holds the string denoting the referrer_id field in the database.
	FieldReferrerID = "referrer_id"
	// FieldBonusAmount holds the string denoting the bonus_amount field in the database.
	FieldBonusAmount = "bonus_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGrantedAt holds the string denoting the granted_at field in the database.
	FieldGrantedAt = "granted_at"
	// FieldGrantedTrigger holds the string denoting the granted_trigger field in the database.
	FieldGrantedTrigger = "granted_trigger"
	// FieldGrantedOrderID holds the string denoting the granted_order_id field in the database.
	FieldGrantedOrderID = "granted_order_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the referralpendingbonus in the database.
	Table = "referral_pending_bonuses"
)

// Columns holds all SQL columns for referralpendingbonus fields.
var Columns = []string{
	FieldID,
	FieldRefereeID,
	FieldReferrerID,
	FieldBonusAmount,
	FieldStatus,
	FieldGrantedAt,
	FieldGrantedTrigger,
	FieldGrantedOrderID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// GrantedTriggerValidator is a validator for the "granted_trigger" field. It is called by the builders before save.
	GrantedTriggerValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralPendingBonus queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRefereeID orders the results by the referee_id field.
func ByRefereeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefereeID, opts...).ToFunc()
}

// ByReferrerID orders the results by the referrer_id field.
func ByReferrerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrerID, opts...).ToFunc()
}

// ByBonusAmount orders the results by the bonus_amount field.
func ByBonusAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGrantedAt orders the results by the granted_at field.
func ByGrantedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedAt, opts...).ToFunc()
}

// ByGrantedTrigger orders the results by the granted_trigger field.
func ByGrantedTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedTrigger, opts...).ToFunc()
}

// ByGrantedOrderID orders the results by the granted_order_id field.
func ByGrantedOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedOrderID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
