// Code generated by ent, DO NOT EDIT.

package invoicevoidrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldUserID, v))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldInvoiceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldStatus, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldReason, v))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldAdminID, v))
}

// AdminNotes applies equality check predicate on the "admin_notes" field. It's identical to AdminNotesEQ.
func AdminNotes(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldAdminNotes, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldUserID, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldInvoiceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldContainsFold(FieldStatus, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldContainsFold(FieldReason, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldAdminID, v))
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldAdminID, v))
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldAdminID, v))
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v int64) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldAdminID, v))
}

// AdminIDIsNil applies the IsNil predicate on the "admin_id" field.
func AdminIDIsNil() predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIsNull(FieldAdminID))
}

// AdminIDNotNil applies the NotNil predicate on the "admin_id" field.
func AdminIDNotNil() predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotNull(FieldAdminID))
}

// AdminNotesEQ applies the EQ predicate on the "admin_notes" field.
func AdminNotesEQ(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldAdminNotes, v))
}

// AdminNotesNEQ applies the NEQ predicate on the "admin_notes" field.
func AdminNotesNEQ(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldAdminNotes, v))
}

// AdminNotesIn applies the In predicate on the "admin_notes" field.
func AdminNotesIn(vs ...string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldAdminNotes, vs...))
}

// AdminNotesNotIn applies the NotIn predicate on the "admin_notes" field.
func AdminNotesNotIn(vs ...string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldAdminNotes, vs...))
}

// AdminNotesGT applies the GT predicate on the "admin_notes" field.
func AdminNotesGT(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldAdminNotes, v))
}

// AdminNotesGTE applies the GTE predicate on the "admin_notes" field.
func AdminNotesGTE(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldAdminNotes, v))
}

// AdminNotesLT applies the LT predicate on the "admin_notes" field.
func AdminNotesLT(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldAdminNotes, v))
}

// AdminNotesLTE applies the LTE predicate on the "admin_notes" field.
func AdminNotesLTE(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldAdminNotes, v))
}

// AdminNotesContains applies the Contains predicate on the "admin_notes" field.
func AdminNotesContains(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldContains(FieldAdminNotes, v))
}

// AdminNotesHasPrefix applies the HasPrefix predicate on the "admin_notes" field.
func AdminNotesHasPrefix(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldHasPrefix(FieldAdminNotes, v))
}

// AdminNotesHasSuffix applies the HasSuffix predicate on the "admin_notes" field.
func AdminNotesHasSuffix(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldHasSuffix(FieldAdminNotes, v))
}

// AdminNotesEqualFold applies the EqualFold predicate on the "admin_notes" field.
func AdminNotesEqualFold(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEqualFold(FieldAdminNotes, v))
}

// AdminNotesContainsFold applies the ContainsFold predicate on the "admin_notes" field.
func AdminNotesContainsFold(v string) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldContainsFold(FieldAdminNotes, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.FieldNotNull(FieldReviewedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceVoidRequest) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceVoidRequest) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceVoidRequest) predicate.InvoiceVoidRequest {
	return predicate.InvoiceVoidRequest(sql.NotPredicates(p))
}
