// Code generated by ent, DO NOT EDIT.

package invoiceitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldID, id))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldInvoiceID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldPaymentOrderID, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderNo, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldProductName, v))
}

// OrderType applies equality check predicate on the "order_type" field. It's identical to OrderTypeEQ.
func OrderType(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderType, v))
}

// PayAmount applies equality check predicate on the "pay_amount" field. It's identical to PayAmountEQ.
func PayAmount(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldPayAmount, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldPaidAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldPaymentOrderID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContainsFold(FieldOrderNo, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContainsFold(FieldProductName, v))
}

// OrderTypeEQ applies the EQ predicate on the "order_type" field.
func OrderTypeEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldOrderType, v))
}

// OrderTypeNEQ applies the NEQ predicate on the "order_type" field.
func OrderTypeNEQ(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldOrderType, v))
}

// OrderTypeIn applies the In predicate on the "order_type" field.
func OrderTypeIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldOrderType, vs...))
}

// OrderTypeNotIn applies the NotIn predicate on the "order_type" field.
func OrderTypeNotIn(vs ...string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldOrderType, vs...))
}

// OrderTypeGT applies the GT predicate on the "order_type" field.
func OrderTypeGT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldOrderType, v))
}

// OrderTypeGTE applies the GTE predicate on the "order_type" field.
func OrderTypeGTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldOrderType, v))
}

// OrderTypeLT applies the LT predicate on the "order_type" field.
func OrderTypeLT(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldOrderType, v))
}

// OrderTypeLTE applies the LTE predicate on the "order_type" field.
func OrderTypeLTE(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldOrderType, v))
}

// OrderTypeContains applies the Contains predicate on the "order_type" field.
func OrderTypeContains(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContains(FieldOrderType, v))
}

// OrderTypeHasPrefix applies the HasPrefix predicate on the "order_type" field.
func OrderTypeHasPrefix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasPrefix(FieldOrderType, v))
}

// OrderTypeHasSuffix applies the HasSuffix predicate on the "order_type" field.
func OrderTypeHasSuffix(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldHasSuffix(FieldOrderType, v))
}

// OrderTypeEqualFold applies the EqualFold predicate on the "order_type" field.
func OrderTypeEqualFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEqualFold(FieldOrderType, v))
}

// OrderTypeContainsFold applies the ContainsFold predicate on the "order_type" field.
func OrderTypeContainsFold(v string) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldContainsFold(FieldOrderType, v))
}

// PayAmountEQ applies the EQ predicate on the "pay_amount" field.
func PayAmountEQ(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldPayAmount, v))
}

// PayAmountNEQ applies the NEQ predicate on the "pay_amount" field.
func PayAmountNEQ(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldPayAmount, v))
}

// PayAmountIn applies the In predicate on the "pay_amount" field.
func PayAmountIn(vs ...float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldPayAmount, vs...))
}

// PayAmountNotIn applies the NotIn predicate on the "pay_amount" field.
func PayAmountNotIn(vs ...float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldPayAmount, vs...))
}

// PayAmountGT applies the GT predicate on the "pay_amount" field.
func PayAmountGT(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldPayAmount, v))
}

// PayAmountGTE applies the GTE predicate on the "pay_amount" field.
func PayAmountGTE(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldPayAmount, v))
}

// PayAmountLT applies the LT predicate on the "pay_amount" field.
func PayAmountLT(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldPayAmount, v))
}

// PayAmountLTE applies the LTE predicate on the "pay_amount" field.
func PayAmountLTE(v float64) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldPayAmount, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldPaidAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInvoice applies the HasEdge predicate on the "invoice" edge.
func HasInvoice() predicate.InvoiceItem {
	return predicate.InvoiceItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceTable, InvoiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceWith applies the HasEdge predicate on the "invoice" edge with a given conditions (other predicates).
func HasInvoiceWith(preds ...predicate.Invoice) predicate.InvoiceItem {
	return predicate.InvoiceItem(func(s *sql.Selector) {
		step := newInvoiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceItem) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceItem) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceItem) predicate.InvoiceItem {
	return predicate.InvoiceItem(sql.NotPredicates(p))
}
