// Code generated by ent, DO NOT EDIT.

package referralcommissionreleaselog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldID, id))
}

// CommissionID applies equality check predicate on the "commission_id" field. It's identical to CommissionIDEQ.
func CommissionID(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldCommissionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldAmount, v))
}

// TriggerType applies equality check predicate on the "trigger_type" field. It's identical to TriggerTypeEQ.
func TriggerType(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldTriggerType, v))
}

// RateSnapshot applies equality check predicate on the "rate_snapshot" field. It's identical to RateSnapshotEQ.
func RateSnapshot(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldRateSnapshot, v))
}

// ComputationDetail applies equality check predicate on the "computation_detail" field. It's identical to ComputationDetailEQ.
func ComputationDetail(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldComputationDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CommissionIDEQ applies the EQ predicate on the "commission_id" field.
func CommissionIDEQ(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldCommissionID, v))
}

// CommissionIDNEQ applies the NEQ predicate on the "commission_id" field.
func CommissionIDNEQ(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldCommissionID, v))
}

// CommissionIDIn applies the In predicate on the "commission_id" field.
func CommissionIDIn(vs ...int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldCommissionID, vs...))
}

// CommissionIDNotIn applies the NotIn predicate on the "commission_id" field.
func CommissionIDNotIn(vs ...int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldCommissionID, vs...))
}

// CommissionIDGT applies the GT predicate on the "commission_id" field.
func CommissionIDGT(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldCommissionID, v))
}

// CommissionIDGTE applies the GTE predicate on the "commission_id" field.
func CommissionIDGTE(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldCommissionID, v))
}

// CommissionIDLT applies the LT predicate on the "commission_id" field.
func CommissionIDLT(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldCommissionID, v))
}

// CommissionIDLTE applies the LTE predicate on the "commission_id" field.
func CommissionIDLTE(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldCommissionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldUserID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldAmount, v))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldTriggerType, vs...))
}

// TriggerTypeGT applies the GT predicate on the "trigger_type" field.
func TriggerTypeGT(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldTriggerType, v))
}

// TriggerTypeGTE applies the GTE predicate on the "trigger_type" field.
func TriggerTypeGTE(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldTriggerType, v))
}

// TriggerTypeLT applies the LT predicate on the "trigger_type" field.
func TriggerTypeLT(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldTriggerType, v))
}

// TriggerTypeLTE applies the LTE predicate on the "trigger_type" field.
func TriggerTypeLTE(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldTriggerType, v))
}

// TriggerTypeContains applies the Contains predicate on the "trigger_type" field.
func TriggerTypeContains(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldContains(FieldTriggerType, v))
}

// TriggerTypeHasPrefix applies the HasPrefix predicate on the "trigger_type" field.
func TriggerTypeHasPrefix(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldHasPrefix(FieldTriggerType, v))
}

// TriggerTypeHasSuffix applies the HasSuffix predicate on the "trigger_type" field.
func TriggerTypeHasSuffix(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldHasSuffix(FieldTriggerType, v))
}

// TriggerTypeEqualFold applies the EqualFold predicate on the "trigger_type" field.
func TriggerTypeEqualFold(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEqualFold(FieldTriggerType, v))
}

// TriggerTypeContainsFold applies the ContainsFold predicate on the "trigger_type" field.
func TriggerTypeContainsFold(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldContainsFold(FieldTriggerType, v))
}

// RateSnapshotEQ applies the EQ predicate on the "rate_snapshot" field.
func RateSnapshotEQ(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldRateSnapshot, v))
}

// RateSnapshotNEQ applies the NEQ predicate on the "rate_snapshot" field.
func RateSnapshotNEQ(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldRateSnapshot, v))
}

// RateSnapshotIn applies the In predicate on the "rate_snapshot" field.
func RateSnapshotIn(vs ...float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldRateSnapshot, vs...))
}

// RateSnapshotNotIn applies the NotIn predicate on the "rate_snapshot" field.
func RateSnapshotNotIn(vs ...float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldRateSnapshot, vs...))
}

// RateSnapshotGT applies the GT predicate on the "rate_snapshot" field.
func RateSnapshotGT(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldRateSnapshot, v))
}

// RateSnapshotGTE applies the GTE predicate on the "rate_snapshot" field.
func RateSnapshotGTE(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldRateSnapshot, v))
}

// RateSnapshotLT applies the LT predicate on the "rate_snapshot" field.
func RateSnapshotLT(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldRateSnapshot, v))
}

// RateSnapshotLTE applies the LTE predicate on the "rate_snapshot" field.
func RateSnapshotLTE(v float64) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldRateSnapshot, v))
}

// ComputationDetailEQ applies the EQ predicate on the "computation_detail" field.
func ComputationDetailEQ(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldComputationDetail, v))
}

// ComputationDetailNEQ applies the NEQ predicate on the "computation_detail" field.
func ComputationDetailNEQ(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldComputationDetail, v))
}

// ComputationDetailIn applies the In predicate on the "computation_detail" field.
func ComputationDetailIn(vs ...string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldComputationDetail, vs...))
}

// ComputationDetailNotIn applies the NotIn predicate on the "computation_detail" field.
func ComputationDetailNotIn(vs ...string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldComputationDetail, vs...))
}

// ComputationDetailGT applies the GT predicate on the "computation_detail" field.
func ComputationDetailGT(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldComputationDetail, v))
}

// ComputationDetailGTE applies the GTE predicate on the "computation_detail" field.
func ComputationDetailGTE(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldComputationDetail, v))
}

// ComputationDetailLT applies the LT predicate on the "computation_detail" field.
func ComputationDetailLT(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldComputationDetail, v))
}

// ComputationDetailLTE applies the LTE predicate on the "computation_detail" field.
func ComputationDetailLTE(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldComputationDetail, v))
}

// ComputationDetailContains applies the Contains predicate on the "computation_detail" field.
func ComputationDetailContains(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldContains(FieldComputationDetail, v))
}

// ComputationDetailHasPrefix applies the HasPrefix predicate on the "computation_detail" field.
func ComputationDetailHasPrefix(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldHasPrefix(FieldComputationDetail, v))
}

// ComputationDetailHasSuffix applies the HasSuffix predicate on the "computation_detail" field.
func ComputationDetailHasSuffix(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldHasSuffix(FieldComputationDetail, v))
}

// ComputationDetailEqualFold applies the EqualFold predicate on the "computation_detail" field.
func ComputationDetailEqualFold(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEqualFold(FieldComputationDetail, v))
}

// ComputationDetailContainsFold applies the ContainsFold predicate on the "computation_detail" field.
func ComputationDetailContainsFold(v string) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldContainsFold(FieldComputationDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommissionReleaseLog) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommissionReleaseLog) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommissionReleaseLog) predicate.ReferralCommissionReleaseLog {
	return predicate.ReferralCommissionReleaseLog(sql.NotPredicates(p))
}
