// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldID, id))
}

// ReferrerID applies equality check predicate on the "referrer_id" field. It's identical to ReferrerIDEQ.
func ReferrerID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReferrerID, v))
}

// RefereeID applies equality check predicate on the "referee_id" field. It's identical to RefereeIDEQ.
func RefereeID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldRefereeID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceType, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceAmount applies equality check predicate on the "source_amount" field. It's identical to SourceAmountEQ.
func SourceAmount(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceAmount, v))
}

// SourceSubscriptionID applies equality check predicate on the "source_subscription_id" field. It's identical to SourceSubscriptionIDEQ.
func SourceSubscriptionID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceSubscriptionID, v))
}

// SourceValidityDays applies equality check predicate on the "source_validity_days" field. It's identical to SourceValidityDaysEQ.
func SourceValidityDays(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceValidityDays, v))
}

// SourceStartsAt applies equality check predicate on the "source_starts_at" field. It's identical to SourceStartsAtEQ.
func SourceStartsAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceStartsAt, v))
}

// CommissionRate applies equality check predicate on the "commission_rate" field. It's identical to CommissionRateEQ.
func CommissionRate(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// GrossCommission applies equality check predicate on the "gross_commission" field. It's identical to GrossCommissionEQ.
func GrossCommission(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldGrossCommission, v))
}

// ReleasedCommission applies equality check predicate on the "released_commission" field. It's identical to ReleasedCommissionEQ.
func ReleasedCommission(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReleasedCommission, v))
}

// ConsumedAttributed applies equality check predicate on the "consumed_attributed" field. It's identical to ConsumedAttributedEQ.
func ConsumedAttributed(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldConsumedAttributed, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReferrerIDEQ applies the EQ predicate on the "referrer_id" field.
func ReferrerIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReferrerID, v))
}

// ReferrerIDNEQ applies the NEQ predicate on the "referrer_id" field.
func ReferrerIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldReferrerID, v))
}

// ReferrerIDIn applies the In predicate on the "referrer_id" field.
func ReferrerIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldReferrerID, vs...))
}

// ReferrerIDNotIn applies the NotIn predicate on the "referrer_id" field.
func ReferrerIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldReferrerID, vs...))
}

// ReferrerIDGT applies the GT predicate on the "referrer_id" field.
func ReferrerIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldReferrerID, v))
}

// ReferrerIDGTE applies the GTE predicate on the "referrer_id" field.
func ReferrerIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldReferrerID, v))
}

// ReferrerIDLT applies the LT predicate on the "referrer_id" field.
func ReferrerIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldReferrerID, v))
}

// ReferrerIDLTE applies the LTE predicate on the "referrer_id" field.
func ReferrerIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldReferrerID, v))
}

// ReferrerIDIsNil applies the IsNil predicate on the "referrer_id" field.
func ReferrerIDIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldReferrerID))
}

// ReferrerIDNotNil applies the NotNil predicate on the "referrer_id" field.
func ReferrerIDNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldReferrerID))
}

// RefereeIDEQ applies the EQ predicate on the "referee_id" field.
func RefereeIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldRefereeID, v))
}

// RefereeIDNEQ applies the NEQ predicate on the "referee_id" field.
func RefereeIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldRefereeID, v))
}

// RefereeIDIn applies the In predicate on the "referee_id" field.
func RefereeIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldRefereeID, vs...))
}

// RefereeIDNotIn applies the NotIn predicate on the "referee_id" field.
func RefereeIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldRefereeID, vs...))
}

// RefereeIDGT applies the GT predicate on the "referee_id" field.
func RefereeIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldRefereeID, v))
}

// RefereeIDGTE applies the GTE predicate on the "referee_id" field.
func RefereeIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldRefereeID, v))
}

// RefereeIDLT applies the LT predicate on the "referee_id" field.
func RefereeIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldRefereeID, v))
}

// RefereeIDLTE applies the LTE predicate on the "referee_id" field.
func RefereeIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldRefereeID, v))
}

// RefereeIDIsNil applies the IsNil predicate on the "referee_id" field.
func RefereeIDIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldRefereeID))
}

// RefereeIDNotNil applies the NotNil predicate on the "referee_id" field.
func RefereeIDNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldRefereeID))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDGT applies the GT predicate on the "source_order_id" field.
func SourceOrderIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceOrderID, v))
}

// SourceOrderIDGTE applies the GTE predicate on the "source_order_id" field.
func SourceOrderIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceOrderID, v))
}

// SourceOrderIDLT applies the LT predicate on the "source_order_id" field.
func SourceOrderIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceOrderID, v))
}

// SourceOrderIDLTE applies the LTE predicate on the "source_order_id" field.
func SourceOrderIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceOrderID, v))
}

// SourceAmountEQ applies the EQ predicate on the "source_amount" field.
func SourceAmountEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceAmount, v))
}

// SourceAmountNEQ applies the NEQ predicate on the "source_amount" field.
func SourceAmountNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceAmount, v))
}

// SourceAmountIn applies the In predicate on the "source_amount" field.
func SourceAmountIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceAmount, vs...))
}

// SourceAmountNotIn applies the NotIn predicate on the "source_amount" field.
func SourceAmountNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceAmount, vs...))
}

// SourceAmountGT applies the GT predicate on the "source_amount" field.
func SourceAmountGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceAmount, v))
}

// SourceAmountGTE applies the GTE predicate on the "source_amount" field.
func SourceAmountGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceAmount, v))
}

// SourceAmountLT applies the LT predicate on the "source_amount" field.
func SourceAmountLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceAmount, v))
}

// SourceAmountLTE applies the LTE predicate on the "source_amount" field.
func SourceAmountLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceAmount, v))
}

// SourceSubscriptionIDEQ applies the EQ predicate on the "source_subscription_id" field.
func SourceSubscriptionIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDNEQ applies the NEQ predicate on the "source_subscription_id" field.
func SourceSubscriptionIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDIn applies the In predicate on the "source_subscription_id" field.
func SourceSubscriptionIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceSubscriptionID, vs...))
}

// SourceSubscriptionIDNotIn applies the NotIn predicate on the "source_subscription_id" field.
func SourceSubscriptionIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceSubscriptionID, vs...))
}

// SourceSubscriptionIDGT applies the GT predicate on the "source_subscription_id" field.
func SourceSubscriptionIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDGTE applies the GTE predicate on the "source_subscription_id" field.
func SourceSubscriptionIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDLT applies the LT predicate on the "source_subscription_id" field.
func SourceSubscriptionIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDLTE applies the LTE predicate on the "source_subscription_id" field.
func SourceSubscriptionIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceSubscriptionID, v))
}

// SourceSubscriptionIDIsNil applies the IsNil predicate on the "source_subscription_id" field.
func SourceSubscriptionIDIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSourceSubscriptionID))
}

// SourceSubscriptionIDNotNil applies the NotNil predicate on the "source_subscription_id" field.
func SourceSubscriptionIDNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSourceSubscriptionID))
}

// SourceValidityDaysEQ applies the EQ predicate on the "source_validity_days" field.
func SourceValidityDaysEQ(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceValidityDays, v))
}

// SourceValidityDaysNEQ applies the NEQ predicate on the "source_validity_days" field.
func SourceValidityDaysNEQ(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceValidityDays, v))
}

// SourceValidityDaysIn applies the In predicate on the "source_validity_days" field.
func SourceValidityDaysIn(vs ...int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceValidityDays, vs...))
}

// SourceValidityDaysNotIn applies the NotIn predicate on the "source_validity_days" field.
func SourceValidityDaysNotIn(vs ...int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceValidityDays, vs...))
}

// SourceValidityDaysGT applies the GT predicate on the "source_validity_days" field.
func SourceValidityDaysGT(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceValidityDays, v))
}

// SourceValidityDaysGTE applies the GTE predicate on the "source_validity_days" field.
func SourceValidityDaysGTE(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceValidityDays, v))
}

// SourceValidityDaysLT applies the LT predicate on the "source_validity_days" field.
func SourceValidityDaysLT(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceValidityDays, v))
}

// SourceValidityDaysLTE applies the LTE predicate on the "source_validity_days" field.
func SourceValidityDaysLTE(v int) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceValidityDays, v))
}

// SourceValidityDaysIsNil applies the IsNil predicate on the "source_validity_days" field.
func SourceValidityDaysIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSourceValidityDays))
}

// SourceValidityDaysNotNil applies the NotNil predicate on the "source_validity_days" field.
func SourceValidityDaysNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSourceValidityDays))
}

// SourceStartsAtEQ applies the EQ predicate on the "source_starts_at" field.
func SourceStartsAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceStartsAt, v))
}

// SourceStartsAtNEQ applies the NEQ predicate on the "source_starts_at" field.
func SourceStartsAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceStartsAt, v))
}

// SourceStartsAtIn applies the In predicate on the "source_starts_at" field.
func SourceStartsAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceStartsAt, vs...))
}

// SourceStartsAtNotIn applies the NotIn predicate on the "source_starts_at" field.
func SourceStartsAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceStartsAt, vs...))
}

// SourceStartsAtGT applies the GT predicate on the "source_starts_at" field.
func SourceStartsAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceStartsAt, v))
}

// SourceStartsAtGTE applies the GTE predicate on the "source_starts_at" field.
func SourceStartsAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceStartsAt, v))
}

// SourceStartsAtLT applies the LT predicate on the "source_starts_at" field.
func SourceStartsAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceStartsAt, v))
}

// SourceStartsAtLTE applies the LTE predicate on the "source_starts_at" field.
func SourceStartsAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceStartsAt, v))
}

// SourceStartsAtIsNil applies the IsNil predicate on the "source_starts_at" field.
func SourceStartsAtIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSourceStartsAt))
}

// SourceStartsAtNotNil applies the NotNil predicate on the "source_starts_at" field.
func SourceStartsAtNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSourceStartsAt))
}

// CommissionRateEQ applies the EQ predicate on the "commission_rate" field.
func CommissionRateEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionRateNEQ applies the NEQ predicate on the "commission_rate" field.
func CommissionRateNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCommissionRate, v))
}

// CommissionRateIn applies the In predicate on the "commission_rate" field.
func CommissionRateIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCommissionRate, vs...))
}

// CommissionRateNotIn applies the NotIn predicate on the "commission_rate" field.
func CommissionRateNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCommissionRate, vs...))
}

// CommissionRateGT applies the GT predicate on the "commission_rate" field.
func CommissionRateGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCommissionRate, v))
}

// CommissionRateGTE applies the GTE predicate on the "commission_rate" field.
func CommissionRateGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCommissionRate, v))
}

// CommissionRateLT applies the LT predicate on the "commission_rate" field.
func CommissionRateLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCommissionRate, v))
}

// CommissionRateLTE applies the LTE predicate on the "commission_rate" field.
func CommissionRateLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCommissionRate, v))
}

// GrossCommissionEQ applies the EQ predicate on the "gross_commission" field.
func GrossCommissionEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldGrossCommission, v))
}

// GrossCommissionNEQ applies the NEQ predicate on the "gross_commission" field.
func GrossCommissionNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldGrossCommission, v))
}

// GrossCommissionIn applies the In predicate on the "gross_commission" field.
func GrossCommissionIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldGrossCommission, vs...))
}

// GrossCommissionNotIn applies the NotIn predicate on the "gross_commission" field.
func GrossCommissionNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldGrossCommission, vs...))
}

// GrossCommissionGT applies the GT predicate on the "gross_commission" field.
func GrossCommissionGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldGrossCommission, v))
}

// GrossCommissionGTE applies the GTE predicate on the "gross_commission" field.
func GrossCommissionGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldGrossCommission, v))
}

// GrossCommissionLT applies the LT predicate on the "gross_commission" field.
func GrossCommissionLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldGrossCommission, v))
}

// GrossCommissionLTE applies the LTE predicate on the "gross_commission" field.
func GrossCommissionLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldGrossCommission, v))
}

// ReleasedCommissionEQ applies the EQ predicate on the "released_commission" field.
func ReleasedCommissionEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReleasedCommission, v))
}

// ReleasedCommissionNEQ applies the NEQ predicate on the "released_commission" field.
func ReleasedCommissionNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldReleasedCommission, v))
}

// ReleasedCommissionIn applies the In predicate on the "released_commission" field.
func ReleasedCommissionIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldReleasedCommission, vs...))
}

// ReleasedCommissionNotIn applies the NotIn predicate on the "released_commission" field.
func ReleasedCommissionNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldReleasedCommission, vs...))
}

// ReleasedCommissionGT applies the GT predicate on the "released_commission" field.
func ReleasedCommissionGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldReleasedCommission, v))
}

// ReleasedCommissionGTE applies the GTE predicate on the "released_commission" field.
func ReleasedCommissionGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldReleasedCommission, v))
}

// ReleasedCommissionLT applies the LT predicate on the "released_commission" field.
func ReleasedCommissionLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldReleasedCommission, v))
}

// ReleasedCommissionLTE applies the LTE predicate on the "released_commission" field.
func ReleasedCommissionLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldReleasedCommission, v))
}

// ConsumedAttributedEQ applies the EQ predicate on the "consumed_attributed" field.
func ConsumedAttributedEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldConsumedAttributed, v))
}

// ConsumedAttributedNEQ applies the NEQ predicate on the "consumed_attributed" field.
func ConsumedAttributedNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldConsumedAttributed, v))
}

// ConsumedAttributedIn applies the In predicate on the "consumed_attributed" field.
func ConsumedAttributedIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldConsumedAttributed, vs...))
}

// ConsumedAttributedNotIn applies the NotIn predicate on the "consumed_attributed" field.
func ConsumedAttributedNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldConsumedAttributed, vs...))
}

// ConsumedAttributedGT applies the GT predicate on the "consumed_attributed" field.
func ConsumedAttributedGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldConsumedAttributed, v))
}

// ConsumedAttributedGTE applies the GTE predicate on the "consumed_attributed" field.
func ConsumedAttributedGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldConsumedAttributed, v))
}

// ConsumedAttributedLT applies the LT predicate on the "consumed_attributed" field.
func ConsumedAttributedLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldConsumedAttributed, v))
}

// ConsumedAttributedLTE applies the LTE predicate on the "consumed_attributed" field.
func ConsumedAttributedLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldConsumedAttributed, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.NotPredicates(p))
}
